import { createStore } from './server/store.mjs';
import { ACTION_LABELS, FIELD_LABELS, ROLE_LABELS, friendlyActor, friendlyError, uiLabel } from '../customer-ui.js';
const store=createStore(),state={selectedId:1,role:'SUBMITTER',quickMode:''},$=id=>document.getElementById(id);
const el={role:$('role'),search:$('search'),statusFilter:$('status-filter'),typeFilter:$('type-filter'),resetFilters:$('reset-filters'),visibleDocCount:$('visible-doc-count'),docList:$('doc-list'),empty:$('empty'),detail:$('detail'),docTitle:$('doc-title'),docMeta:$('doc-meta'),docPreview:$('doc-preview'),version:$('version'),status:$('status'),type:$('type'),checkResult:$('check-result'),checklist:$('checklist'),editSection:$('edit-section'),metadataFields:$('metadata-fields'),source:$('source'),save:$('save'),extract:$('extract'),submit:$('submit'),reviewSection:$('review-section'),comment:$('comment'),archive:$('archive'),message:$('message'),reviewQueue:$('review-queue'),auditList:$('audit-list'),mDraft:$('m-draft'),mSubmitted:$('m-submitted'),mChanges:$('m-changes'),mApproved:$('m-approved'),mRejected:$('m-rejected'),qSubmitted:$('q-submitted'),qChanges:$('q-changes'),qIncomplete:$('q-incomplete'),intakeType:$('intake-type'),intakeTitle:$('intake-title'),intakeSource:$('intake-source'),createDocument:$('create-document')};
const node=(t,c='',x='')=>{const n=document.createElement(t);if(c)n.className=c;if(x)n.textContent=textValue(x);return n;};const textValue=v=>String(v??'');const badge=v=>node('span',`badge ${v}`,uiLabel(v));const actor=()=>state.role==='ADMIN'?'demo-admin':state.role==='REVIEWER'?'demo-reviewer':'submitter';
const dateText=v=>{if(!v)return'시간 정보 없음';const d=new Date(v);return Number.isNaN(d.getTime())?'시간 정보 없음':new Intl.DateTimeFormat('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d);};
function doc(){try{return store.getDocument(state.selectedId);}catch{return null;}}function msg(x,e=false){el.message.textContent=x;el.message.dataset.error=e?'true':'false';}
function metrics(){const m=store.metrics(),drafts=store.listDocuments({status:'DRAFT'});el.mDraft.textContent=m.draft;el.mSubmitted.textContent=m.submitted;el.mChanges.textContent=m.needsChanges;el.mApproved.textContent=m.approved;el.mRejected.textContent=m.rejected;el.qSubmitted.textContent=`${m.submitted}건`;el.qChanges.textContent=`${m.needsChanges}건`;el.qIncomplete.textContent=`${drafts.filter(d=>!d.checklist.valid).length}건`;}
function filteredDocs(){let docs=store.listDocuments({query:el.search.value,status:el.statusFilter.value,type:el.typeFilter.value});if(state.quickMode==='DRAFT_INCOMPLETE')docs=docs.filter(d=>d.status==='DRAFT'&&!d.checklist.valid);return docs;}
function list(){const docs=filteredDocs();el.visibleDocCount.textContent=`${docs.length}건`;el.docList.replaceChildren();for(const d of docs){const b=node('button',`doc-card${d.id===state.selectedId?' active':''}`);b.type='button';b.dataset.docId=String(d.id);const h=node('div','card-head');h.append(node('strong','',`#${d.id} ${d.title}`),badge(d.status));b.append(h,node('p','',`${uiLabel(d.type)} · ${d.checklist.valid?'필수 항목 확인 완료':'필수 항목 확인 필요'}`),node('small','',`${d.reviewer?`${friendlyActor(d.reviewer)} 검토`:'아직 검토 전'} · v${d.version}`));b.addEventListener('click',()=>{state.selectedId=d.id;msg('');render();});el.docList.append(b);}if(!docs.length)el.docList.append(node('div','empty compact','조건에 맞는 문서가 없습니다.'));}
function renderMetadata(d){el.metadataFields.replaceChildren();const keys=[...new Set([...d.checklist.items.map(i=>i.field),...Object.keys(d.metadata)])];for(const key of keys){const label=node('label','');label.append(node('span','',FIELD_LABELS[key]??key));const input=document.createElement('input');input.type=key==='amount'?'number':key==='effectiveDate'?'date':key==='email'?'email':'text';input.dataset.field=key;input.value=textValue(d.metadata[key]);label.append(input);el.metadataFields.append(label);}}
function readMetadata(){const result={};for(const input of el.metadataFields.querySelectorAll('[data-field]'))result[input.dataset.field]=input.value.trim();return result;}
function renderPreview(d){el.docPreview.replaceChildren();const paper=node('article','paper');const head=node('div','paper-header');head.append(node('span','',uiLabel(d.type)),node('strong','',d.title));paper.append(head);const meta=node('div','paper-meta');const keys=[...new Set([...d.checklist.items.map(i=>i.field),...Object.keys(d.metadata)])];for(const key of keys){const box=node('div','');box.append(node('span','',FIELD_LABELS[key]??key),node('strong','',textValue(d.metadata[key])||'—'));meta.append(box);}paper.append(meta);const source=node('div','paper-source');source.append(node('h3','','원문 내용'),node('p','',d.sourceText||'원문 내용이 없습니다.'));paper.append(source);el.docPreview.append(paper);}
function detail(){const d=doc();el.empty.hidden=Boolean(d);el.detail.hidden=!d;if(!d)return;el.docTitle.textContent=`#${d.id} · ${d.title}`;el.docMeta.textContent=`최근 업데이트 ${dateText(d.updatedAt)}${d.reviewComment?` · 검수 메모: ${d.reviewComment}`:' · 아직 검수 메모가 없습니다.'}`;el.version.textContent=`v${d.version}`;el.status.textContent=uiLabel(d.status);el.type.textContent=uiLabel(d.type);el.checkResult.textContent=d.checklist.valid?'확인 완료':'확인 필요';renderPreview(d);el.checklist.replaceChildren();for(const i of d.checklist.items){const row=node('div',`check-row ${i.ok?'ok':'fail'}`);row.append(node('strong','',FIELD_LABELS[i.field]??i.field),node('span','',i.ok?'입력됨':'값을 입력해 주세요'));el.checklist.append(row);}const canEdit=state.role==='SUBMITTER'&&d.allowedActions.includes('EDIT');el.editSection.hidden=!canEdit;if(canEdit){renderMetadata(d);el.source.value=d.sourceText||'';}const canReview=['REVIEWER','ADMIN'].includes(state.role)&&d.allowedActions.includes('REVIEW');el.reviewSection.hidden=!canReview;for(const b of el.reviewSection.querySelectorAll('button'))b.disabled=!canReview;const canArchive=state.role==='ADMIN'&&d.allowedActions.includes('ARCHIVE');el.archive.hidden=!canArchive;el.archive.disabled=!canArchive;}
function refreshAction(action){const d=doc();if(!d)return;try{if(action==='SAVE'){store.update(d.id,{expectedVersion:d.version,metadata:readMetadata(),sourceText:el.source.value,actor:actor(),role:state.role});msg('문서 수정을 저장했습니다.');}else if(action==='EXTRACT'){store.extract(d.id,{expectedVersion:d.version,actor:actor(),role:state.role});msg('원문에서 값을 채웠습니다.');}else if(action==='SUBMIT'){store.submit(d.id,{expectedVersion:d.version,actor:actor(),role:state.role});msg('검수 요청을 제출했습니다.');}}catch(e){msg(friendlyError(e),true);}render();}
function review(decision){const d=doc();if(!d)return;const comment=el.comment.value.trim();if(comment.length<4){msg('검수 근거를 4자 이상 입력해 주세요.',true);return;}try{store.review(d.id,{expectedVersion:d.version,decision,comment,reviewer:actor(),role:state.role});el.comment.value='';msg(decision==='APPROVE'?'문서를 승인했습니다.':decision==='NEEDS_CHANGES'?'작성자에게 수정을 요청했습니다.':'문서를 반려했습니다.');}catch(e){msg(friendlyError(e,'검수 결과를 처리할 수 없습니다.'),true);}render();}
function queue(){const docs=store.listDocuments({status:'SUBMITTED'});el.reviewQueue.replaceChildren();if(!docs.length){el.reviewQueue.append(node('div','empty compact','현재 검수 대기 문서가 없습니다.'));return;}for(const d of docs){const r=node('button','queue-row');r.type='button';r.dataset.docId=String(d.id);r.append(node('strong','',`#${d.id} ${d.title}`),node('span','',`${uiLabel(d.type)} · v${d.version}`));r.addEventListener('click',()=>{state.selectedId=d.id;msg('');render();});el.reviewQueue.append(r);}}
function audits(){el.auditList.replaceChildren();for(const a of store.listAudits().slice(0,24)){const r=node('article','audit');const h=node('div');h.append(node('strong','',`${ACTION_LABELS[a.action]??uiLabel(a.action)} · 문서 #${a.documentId}`),node('span','',`${friendlyActor(a.actor)} · v${a.documentVersion}`));r.append(h,node('p','',a.detail||'상태 변경'));el.auditList.append(r);}}
function render(){metrics();list();detail();queue();audits();el.createDocument.disabled=state.role!=='SUBMITTER';}
function resetFilters(){state.quickMode='';el.search.value='';el.statusFilter.value='';el.typeFilter.value='';list();}
function createNewDocument(){if(state.role!=='SUBMITTER'){msg('새 문서 접수는 문서 작성자 권한에서만 가능합니다.',true);return;}try{const created=store.createDocument({type:el.intakeType.value,title:el.intakeTitle.value,sourceText:el.intakeSource.value,metadata:{},actor:actor(),role:state.role});state.selectedId=created.id;el.intakeTitle.value='';el.intakeSource.value='';resetFilters();msg('새 문서를 접수했습니다. 원문에서 값을 채우거나 직접 입력한 뒤 검수 요청하세요.');render();}catch(e){msg(friendlyError(e,'문서 제목과 접수 내용을 다시 확인해 주세요.'),true);}}
el.role.addEventListener('change',()=>{state.role=el.role.value;msg(`${ROLE_LABELS[state.role]} 화면으로 전환했습니다.`);render();});
el.search.addEventListener('input',()=>{state.quickMode='';list();});el.statusFilter.addEventListener('change',()=>{state.quickMode='';list();});el.typeFilter.addEventListener('change',()=>{state.quickMode='';list();});el.resetFilters.addEventListener('click',resetFilters);
document.querySelector('.priority-board').addEventListener('click',e=>{const b=e.target.closest('button[data-quick-filter]');if(!b)return;const mode=b.dataset.quickFilter;el.search.value='';el.typeFilter.value='';state.quickMode=mode==='DRAFT_INCOMPLETE'?'DRAFT_INCOMPLETE':'';el.statusFilter.value=mode==='DRAFT_INCOMPLETE'?'DRAFT':mode;list();});
el.createDocument.addEventListener('click',createNewDocument);el.save.addEventListener('click',()=>refreshAction('SAVE'));el.extract.addEventListener('click',()=>refreshAction('EXTRACT'));el.submit.addEventListener('click',()=>refreshAction('SUBMIT'));el.reviewSection.addEventListener('click',e=>{const b=e.target.closest('button[data-decision]');if(b)review(b.dataset.decision);});el.archive.addEventListener('click',()=>{const d=doc();if(!d)return;try{store.archive(d.id,{expectedVersion:d.version,role:state.role,actor:actor()});msg('문서를 보관 처리했습니다.');}catch(e){msg(friendlyError(e),true);}render();});render();
