export const DOCUMENT_STATUS=Object.freeze({DRAFT:'DRAFT',SUBMITTED:'SUBMITTED',NEEDS_CHANGES:'NEEDS_CHANGES',APPROVED:'APPROVED',REJECTED:'REJECTED',ARCHIVED:'ARCHIVED'});
export const DOCUMENT_TYPES=Object.freeze(['INVOICE','APPLICATION','CONTRACT']);
export const REQUIRED_FIELDS=Object.freeze({INVOICE:['documentNo','party','amount'],APPLICATION:['applicantName','email'],CONTRACT:['documentNo','counterparty','effectiveDate']});
const txt=v=>String(v??'').trim();const clone=v=>structuredClone(v);
export function assertExpectedVersion(doc,v){const n=Number(v);if(!Number.isInteger(n)||n<1)throw new Error('expectedVersion must be a positive integer');if(doc.version!==n)throw new Error(`STALE_DOCUMENT_VERSION:${n}:${doc.version}`);}
export function normalizeMetadata(type,input={}){const out={};for(const [k,v] of Object.entries(input||{})){const val=txt(v);if(val)out[k]=val.slice(0,300);}if(type==='INVOICE'&&out.amount){const n=Number(String(out.amount).replaceAll(',',''));if(!Number.isFinite(n)||n<=0)throw new Error('invoice amount must be positive');out.amount=String(Math.round(n));}if(type==='APPLICATION'&&out.email&&!/^\S+@\S+\.\S+$/.test(out.email))throw new Error('application email must be valid');if(type==='CONTRACT'&&out.effectiveDate&&Number.isNaN(new Date(out.effectiveDate).getTime()))throw new Error('effectiveDate must be a valid date');return out;}
export function extractMetadata(type,text){const source=String(text??'');const map={};for(const line of source.split(/\r?\n/)){const m=line.match(/^\s*([A-Za-z][A-Za-z0-9_ ]{1,40})\s*:\s*(.+?)\s*$/);if(m){const key=m[1].trim().replace(/\s+(.)/g,(_,c)=>c.toUpperCase());map[key.charAt(0).toLowerCase()+key.slice(1)]=m[2].trim();}}return normalizeMetadata(type,map);}
export function validateChecklist(doc){const required=REQUIRED_FIELDS[doc.type]??[];const items=required.map(field=>({field,ok:Boolean(txt(doc.metadata?.[field])),message:txt(doc.metadata?.[field])?'OK':`${field} is required`}));return{valid:items.every(i=>i.ok),items};}
export function createDocument(input,meta={}){const type=txt(input?.type).toUpperCase(),title=txt(input?.title);if(!DOCUMENT_TYPES.includes(type))throw new Error('unsupported document type');if(title.length<3||title.length>120)throw new Error('title must be 3-120 characters');const metadata=normalizeMetadata(type,input?.metadata||{});return{id:Number(meta.id),type,title,status:DOCUMENT_STATUS.DRAFT,metadata,sourceText:txt(input?.sourceText).slice(0,5000),version:1,reviewComment:null,reviewer:null,createdAt:txt(meta.createdAt),updatedAt:txt(meta.createdAt)};}
function changed(doc,patch,ts=''){return{...doc,...patch,version:doc.version+1,updatedAt:ts||doc.updatedAt};}
export function updateDocument(doc,input,ts=''){if(![DOCUMENT_STATUS.DRAFT,DOCUMENT_STATUS.NEEDS_CHANGES].includes(doc.status))throw new Error('document is not editable');const metadata=input?.metadata?normalizeMetadata(doc.type,input.metadata):doc.metadata;const title=input?.title!==undefined?txt(input.title):doc.title;if(title.length<3||title.length>120)throw new Error('title must be 3-120 characters');return changed(doc,{title,metadata,sourceText:input?.sourceText!==undefined?txt(input.sourceText).slice(0,5000):doc.sourceText,reviewComment:null,reviewer:null},ts);}
export function applyExtraction(doc,ts=''){if(![DOCUMENT_STATUS.DRAFT,DOCUMENT_STATUS.NEEDS_CHANGES].includes(doc.status))throw new Error('document is not editable');const extracted=extractMetadata(doc.type,doc.sourceText);return changed(doc,{metadata:{...doc.metadata,...extracted}},ts);}
export function submitDocument(doc,ts=''){if(![DOCUMENT_STATUS.DRAFT,DOCUMENT_STATUS.NEEDS_CHANGES].includes(doc.status))throw new Error('document cannot be submitted');const checklist=validateChecklist(doc);if(!checklist.valid)throw new Error('CHECKLIST_INCOMPLETE');return changed(doc,{status:DOCUMENT_STATUS.SUBMITTED,reviewComment:null,reviewer:null},ts);}
export function reviewDocument(doc,input,ts=''){if(doc.status!==DOCUMENT_STATUS.SUBMITTED)throw new Error('only submitted documents can be reviewed');const decision=txt(input?.decision).toUpperCase(),comment=txt(input?.comment).slice(0,500),reviewer=txt(input?.reviewer||'reviewer').slice(0,80);if(!['APPROVE','NEEDS_CHANGES','REJECT'].includes(decision))throw new Error('unsupported review decision');if(['NEEDS_CHANGES','REJECT'].includes(decision)&&comment.length<3)throw new Error('review comment is required');const status=decision==='APPROVE'?DOCUMENT_STATUS.APPROVED:decision==='REJECT'?DOCUMENT_STATUS.REJECTED:DOCUMENT_STATUS.NEEDS_CHANGES;return changed(doc,{status,reviewComment:comment||null,reviewer},ts);}
export function archiveDocument(doc,ts=''){if(![DOCUMENT_STATUS.APPROVED,DOCUMENT_STATUS.REJECTED].includes(doc.status))throw new Error('only finalized documents can be archived');return changed(doc,{status:DOCUMENT_STATUS.ARCHIVED},ts);}
export function allowedActions(doc){if([DOCUMENT_STATUS.DRAFT,DOCUMENT_STATUS.NEEDS_CHANGES].includes(doc.status))return['EDIT','EXTRACT','SUBMIT'];if(doc.status===DOCUMENT_STATUS.SUBMITTED)return['REVIEW'];if([DOCUMENT_STATUS.APPROVED,DOCUMENT_STATUS.REJECTED].includes(doc.status))return['ARCHIVE'];return[];}
export function computeMetrics(docs){return{draft:docs.filter(d=>d.status===DOCUMENT_STATUS.DRAFT).length,submitted:docs.filter(d=>d.status===DOCUMENT_STATUS.SUBMITTED).length,needsChanges:docs.filter(d=>d.status===DOCUMENT_STATUS.NEEDS_CHANGES).length,approved:docs.filter(d=>d.status===DOCUMENT_STATUS.APPROVED).length,rejected:docs.filter(d=>d.status===DOCUMENT_STATUS.REJECTED).length};}
export function snapshotDocument(doc){return clone({...doc,checklist:validateChecklist(doc),allowedActions:allowedActions(doc)});}
