import { TASK_STATUS, applyHumanReview, nextTaskStatus, runGeneration, validateStructuredOutput, validateTaskInput } from './engine.mjs';
import { listKnowledgeDocuments } from './knowledge.mjs';
import { CATEGORY_LABELS, STATUS_LABELS, uiLabel } from '../customer-ui.js';

const state={taskSeq:4,runSeq:1,reviewSeq:1,selectedId:1,tasks:[
{id:1,title:'중복 결제 환불 문의',content:'이번 달 청구서에 같은 금액이 두 번 결제되었습니다. 환불 가능 여부를 확인해 주세요.',status:TASK_STATUS.PENDING,version:1,output:null,evaluation:null,retrieval:null,lastRun:null},
{id:2,title:'직원 계정 로그인 불가',content:'긴급: 권한 변경 이후 직원이 운영 계정에 로그인하지 못하고 있습니다. 필요한 확인 절차를 알려주세요.',status:TASK_STATUS.PENDING,version:1,output:null,evaluation:null,retrieval:null,lastRun:null},
{id:3,title:'거래처 Excel 업로드 오류',content:'[FAIL_PRIMARY] 거래처가 보내는 Excel 파일의 컬럼명이 바뀌어 업로드에 실패합니다. 어떤 항목부터 확인해야 하나요?',status:TASK_STATUS.PENDING,version:1,output:null,evaluation:null,retrieval:null,lastRun:null}
],runs:[],reviews:[]};
const $=id=>document.getElementById(id);const elements={pendingCount:$('pending-count'),reviewCount:$('review-count'),finalCount:$('final-count'),fallbackCount:$('fallback-count'),taskForm:$('task-form'),taskTitle:$('task-title'),taskContent:$('task-content'),taskList:$('task-list'),generateAll:$('generate-all'),promptVersion:$('prompt-version'),emptyReview:$('empty-review'),reviewContent:$('review-content'),selectedStatus:$('selected-status'),selectedTitle:$('selected-title'),selectedInput:$('selected-input'),generateSelected:$('generate-selected'),providerTrace:$('provider-trace'),outputEditor:$('output-editor'),providerName:$('provider-name'),promptName:$('prompt-name'),evalScore:$('eval-score'),evalFlags:$('eval-flags'),evidenceCoverage:$('evidence-coverage'),evidenceCount:$('evidence-count'),evidenceList:$('evidence-list'),knowledgeList:$('knowledge-list'),editSummary:$('edit-summary'),editAction:$('edit-action'),editCategory:$('edit-category'),editRisk:$('edit-risk'),editConfidence:$('edit-confidence'),approve:$('approve'),reject:$('reject'),runHistory:$('run-history'),reviewHistory:$('review-history')};
const selectedTask=()=>state.tasks.find(t=>t.id===state.selectedId)??null;const make=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};const statusBadge=s=>make('span',`status ${s}`,uiLabel(s));
const flagLabels={EVIDENCE_FOUND:'참고자료 확인됨',LOW_EVIDENCE_COVERAGE:'참고자료 추가 확인',NO_EVIDENCE:'직접 확인 필요',HIGH_RISK:'중요도 높음',MEDIUM_RISK:'중요도 보통',LOW_CONFIDENCE:'자동 판단 확인 필요',PROVIDER_FAILURE:'대체 처리 사용'};
function cleanInput(v){return String(v??'').replaceAll('[FAIL_PRIMARY]','').replaceAll('[FAIL_ALL]','').trim();}
function renderStats(){elements.pendingCount.textContent=String(state.tasks.filter(t=>t.status===TASK_STATUS.PENDING).length);elements.reviewCount.textContent=String(state.tasks.filter(t=>[TASK_STATUS.GENERATED,TASK_STATUS.NEEDS_REVIEW].includes(t.status)).length);elements.finalCount.textContent=String(state.tasks.filter(t=>[TASK_STATUS.APPROVED,TASK_STATUS.REJECTED].includes(t.status)).length);elements.fallbackCount.textContent=String(state.runs.filter(r=>r.attempts.length>1&&r.status==='SUCCESS').length);}
function renderTaskList(){elements.taskList.replaceChildren();for(const task of state.tasks){const b=make('button',`task-card${task.id===state.selectedId?' active':''}`);b.type='button';b.addEventListener('click',()=>{state.selectedId=task.id;render();});const h=document.createElement('header');h.append(make('strong','',task.title),statusBadge(task.status));const meta=task.retrieval?.evidence?.length?`참고자료 ${task.retrieval.evidence.length}건`:'아직 자동 정리 전';b.append(h,make('p','',cleanInput(task.content)),make('small','',meta));elements.taskList.append(b);}}
function renderTrace(task){elements.providerTrace.replaceChildren();if(!task?.lastRun)return;const failed=task.lastRun.attempts.filter(a=>a.status!=='SUCCESS').length;const succeeded=task.lastRun.status==='SUCCESS';if(failed&&succeeded)elements.providerTrace.append(make('span','ok','첫 처리에 실패해 자동으로 대체 방식으로 다시 처리했습니다.'));else if(!succeeded)elements.providerTrace.append(make('span','fail','자동 정리에 실패했습니다. 담당자가 직접 확인해 주세요.'));else elements.providerTrace.append(make('span','ok','자동 정리가 완료되었습니다.'));}
function renderEvidence(task){elements.evidenceList.replaceChildren();const retrieval=task?.lastRun?.retrieval??task?.retrieval??null;const evidence=retrieval?.evidence??[];elements.evidenceCount.textContent=`${evidence.length}건`;elements.evidenceCoverage.textContent=retrieval?`${Math.round(retrieval.coverage*100)}%`:'-';if(!evidence.length){elements.evidenceList.append(make('div','evidence-empty','관련 자료를 찾지 못했습니다. 담당자가 직접 확인해야 합니다.'));return;}for(const item of evidence){const article=make('article','evidence-item');const header=document.createElement('header');const source=make('div','');source.append(make('strong','',`${item.rank}. ${item.title}`),make('span','',item.section));header.append(source,make('b','',`관련도 ${Math.min(100,Math.round(item.score*5))}%`));article.append(header,make('p','',item.excerpt));elements.evidenceList.append(article);}}
function fillOutput(task){const ready=Boolean(task?.output&&[TASK_STATUS.GENERATED,TASK_STATUS.NEEDS_REVIEW].includes(task.status));elements.outputEditor.hidden=!ready;if(!ready)return;elements.providerName.textContent=task.lastRun?.attempts?.length>1?'대체 처리':'기본 처리';elements.promptName.textContent='업무 정리';elements.evalScore.textContent=`${task.evaluation?.score??'-'} / 100`;elements.evalFlags.textContent=task.evaluation?.flags?.length?task.evaluation.flags.map(f=>flagLabels[f]??'추가 확인').join(' · '):'추가 확인 없음';elements.editSummary.value=task.output.summary;elements.editAction.value=task.output.nextAction;elements.editCategory.value=task.output.category;elements.editRisk.value=task.output.risk;elements.editConfidence.value=String(task.output.confidence);renderEvidence(task);}
function renderReviewDesk(){const task=selectedTask();elements.emptyReview.hidden=Boolean(task);elements.reviewContent.hidden=!task;if(!task)return;elements.selectedStatus.className=`status ${task.status}`;elements.selectedStatus.textContent=uiLabel(task.status);elements.selectedTitle.textContent=task.title;elements.selectedInput.textContent=cleanInput(task.content);const finalized=[TASK_STATUS.APPROVED,TASK_STATUS.REJECTED].includes(task.status);elements.generateSelected.disabled=finalized;elements.generateSelected.textContent=task.lastRun?'관련 자료 다시 찾고 정리하기':'관련 자료 찾고 정리하기';renderTrace(task);fillOutput(task);}
function historyItem(title,detail){const article=make('article','history-item');const header=document.createElement('header');header.append(make('strong','',title));article.append(header,make('p','',detail));return article;}
function renderHistory(){elements.runHistory.replaceChildren();if(!state.runs.length)elements.runHistory.append(make('div','empty-state compact-empty','아직 자동 처리 이력이 없습니다.'));for(const run of [...state.runs].reverse()){const evidence=run.retrieval?.evidence?.length??0;const detail=run.status==='SUCCESS'?`자동 정리 완료 · 참고자료 ${evidence}건 · 점검 ${run.evaluation.score}/100`:'자동 처리 실패 · 담당자 직접 확인 필요';elements.runHistory.append(historyItem(`문의 #${run.taskId}`,detail));}elements.reviewHistory.replaceChildren();if(!state.reviews.length)elements.reviewHistory.append(make('div','empty-state compact-empty','아직 담당자 승인·반려 기록이 없습니다.'));for(const review of [...state.reviews].reverse()){elements.reviewHistory.append(historyItem(`문의 #${review.taskId} · ${review.decision==='APPROVE'?'승인':'반려'}`,`${review.edited?'내용을 수정한 뒤 결정':'제안 내용 그대로 결정'} · 참고자료 ${review.evidenceIds.length}건`));}}
function renderKnowledge(){elements.knowledgeList.replaceChildren();for(const document of listKnowledgeDocuments()){const article=make('article','knowledge-item');article.append(make('span','knowledge-category',CATEGORY_LABELS[document.category]??'업무자료'),make('strong','',document.title),make('p','',`${document.sectionCount}개 확인 항목`));elements.knowledgeList.append(article);}}
function render(){renderStats();renderTaskList();renderReviewDesk();renderHistory();renderKnowledge();elements.generateAll.disabled=!state.tasks.some(t=>t.status===TASK_STATUS.PENDING);}
function generateTask(task){if([TASK_STATUS.APPROVED,TASK_STATUS.REJECTED].includes(task.status))return;const result=runGeneration(task,{promptVersion:elements.promptVersion.value});const runRecord={id:state.runSeq++,taskId:task.id,...result,createdAt:new Date().toISOString()};state.runs.push(runRecord);task.version+=1;task.lastRun=runRecord;task.evaluation=result.evaluation;task.retrieval=result.retrieval;if(result.status==='SUCCESS'){task.output=result.output;task.status=nextTaskStatus(result);}else{task.output=null;task.status=TASK_STATUS.PENDING;}}
function editorOutput(){return{summary:elements.editSummary.value.trim(),category:elements.editCategory.value,risk:elements.editRisk.value,nextAction:elements.editAction.value.trim(),confidence:Number(elements.editConfidence.value)};}
function reviewSelected(decision){const task=selectedTask();if(!task)return;const edited=editorOutput();if(decision==='APPROVE'&&!validateStructuredOutput(edited)){window.alert('핵심 내용, 다음 처리, 신뢰도 값을 다시 확인해 주세요.');return;}try{const before=JSON.stringify(task.output);Object.assign(task,applyHumanReview(task,decision,decision==='APPROVE'?edited:null));state.reviews.push({id:state.reviewSeq++,taskId:task.id,decision,reviewer:'demo-reviewer',version:task.version,edited:decision==='APPROVE'&&before!==JSON.stringify(edited),evidenceIds:task.retrieval?.evidence?.map(i=>i.id)??[],evidenceCoverage:task.retrieval?.coverage??0,createdAt:new Date().toISOString()});render();}catch(error){window.alert(error instanceof Error?'현재 상태에서는 이 항목을 처리할 수 없습니다.':'처리에 실패했습니다.');}}
elements.taskForm.addEventListener('submit',event=>{event.preventDefault();try{const input=validateTaskInput({title:elements.taskTitle.value,content:elements.taskContent.value});const task={id:state.taskSeq++,...input,status:TASK_STATUS.PENDING,version:1,output:null,evaluation:null,retrieval:null,lastRun:null};state.tasks.unshift(task);state.selectedId=task.id;elements.taskForm.reset();render();}catch{window.alert('제목과 내용을 입력해 주세요.');}});
elements.generateSelected.addEventListener('click',()=>{const task=selectedTask();if(task){generateTask(task);render();}});elements.generateAll.addEventListener('click',()=>{for(const task of state.tasks)if(task.status===TASK_STATUS.PENDING)generateTask(task);render();});elements.approve.addEventListener('click',()=>reviewSelected('APPROVE'));elements.reject.addEventListener('click',()=>reviewSelected('REJECT'));render();
