const state={csrf:sessionStorage.getItem('mono.csrf')||'',user:null,view:'dashboard',work:[],orders:[],documents:[],support:[],connections:[],jobs:[],runs:[],dead:[]};
const $=(s,r=document)=>r.querySelector(s);const $$=(s,r=document)=>[...r.querySelectorAll(s)];
function escapeHtml(value){return String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function toast(text){const el=$('#toast');el.textContent=text;el.classList.add('show');clearTimeout(toast.t);toast.t=setTimeout(()=>el.classList.remove('show'),2200)}
function message(name,text=''){const el=$(`[data-message="${name}"]`);if(el)el.textContent=text}
async function api(path,{method='GET',body,headers={}}={}){const options={method,credentials:'same-origin',headers:{...headers}};if(body!==undefined){options.headers['content-type']='application/json';options.body=JSON.stringify(body)}if(method!=='GET'&&method!=='HEAD'&&state.csrf)options.headers['x-csrf-token']=state.csrf;const response=await fetch(path,options);let payload={};try{payload=await response.json()}catch{}if(response.status===401){showLogin();throw new Error('UNAUTHORIZED')}if(!response.ok){const error=new Error(payload.error||`HTTP_${response.status}`);error.code=payload.error||`HTTP_${response.status}`;throw error}return payload}
function showLogin(){state.user=null;$('#app-shell').hidden=true;$('#login-screen').hidden=false}
function showApp(){$('#login-screen').hidden=true;$('#app-shell').hidden=false;$('#user-name').textContent=state.user.name;$('#user-role').textContent=state.user.role;$('#side-user').textContent=state.user.email;loadView(state.view)}
function can(cap){const role=state.user?.role;if(role==='ADMIN')return true;const caps={OPERATOR:['orders.create','orders.fulfill','refunds.create','documents.write','documents.submit','support.create','support.generate'],REVIEWER:['documents.review','support.review'],MANAGER:['orders.create','orders.fulfill','refunds.create','refunds.approve','documents.write','documents.submit','documents.review','support.create','support.generate','support.review','integrations.retry','audit.read']}[role]||[];return caps.includes(cap)}
function formatMoney(cents){return `${Math.round(Number(cents||0)/100).toLocaleString('ko-KR')}원`}
function titleFor(view){return {dashboard:'통합 업무함',market:'MARKET · 주문 운영',office:'OFFICE · 문서 운영',support:'SUPPORT · 고객지원',datahub:'DATA HUB · 데이터 연동',audit:'감사이력'}[view]||'MONO OPERATIONS'}
async function setView(view){state.view=view;$$('.sidebar nav button').forEach(b=>b.classList.toggle('active',b.dataset.view===view));$$('.view').forEach(v=>v.classList.toggle('active',v.dataset.panel===view));$('#view-title').textContent=titleFor(view);$('#sidebar').classList.remove('open');await loadView(view)}
async function loadView(view){try{if(view==='dashboard')await loadDashboard();if(view==='market')await loadOrders();if(view==='office')await loadDocuments();if(view==='support')await loadSupport();if(view==='datahub')await loadIntegrations();if(view==='audit')await loadAudit()}catch(error){toast(`불러오기 실패: ${error.code||error.message}`)}}

async function loadDashboard(){const {items}=await api('/api/work-items');state.work=items;const high=items.filter(i=>i.priority==='HIGH').length,available=items.filter(i=>i.canAct&&i.status!=='확인 완료').length,blocked=items.filter(i=>!i.canAct).length,done=items.filter(i=>i.status==='확인 완료').length;$('#metrics').innerHTML=[[items.length,'전체 업무'],[high,'긴급'],[available,'내가 처리 가능'],[done,'확인 완료']].map(([n,l])=>`<article><span>${l}</span><strong>${n}</strong><small>${blocked&&l==='내가 처리 가능'?`권한 제한 ${blocked}건`: '현재 DB 기준'}</small></article>`).join('');renderWork()}
function renderWork(){const filter=$('#work-filter').value;const items=state.work.filter(i=>filter==='ALL'||i.module===filter);$('#work-list').innerHTML=items.length?items.map(i=>`<article class="work-row"><span class="module">${escapeHtml(i.module)}</span><div><strong>${escapeHtml(i.title)}</strong><small>${escapeHtml(i.subtitle)} · ${escapeHtml(i.status)} · v${i.version}</small></div><div class="actions"><span class="badge ${i.priority==='HIGH'?'high':''}">${escapeHtml(i.priority)}</span><button class="action ${i.canAct?'primary-action':''}" data-ack="${escapeHtml(i.id)}" ${!i.canAct||i.status==='확인 완료'?'disabled':''}>${i.status==='확인 완료'?'처리됨':i.canAct?'확인 처리':'권한 필요'}</button></div></article>`).join(''):'<div class="empty">표시할 업무가 없습니다.</div>';$$('[data-ack]').forEach(btn=>btn.addEventListener('click',async()=>{const item=state.work.find(i=>i.id===btn.dataset.ack);try{await api(`/api/work-items/${encodeURIComponent(item.id)}/acknowledge`,{method:'POST',body:{expectedVersion:item.version}});toast('업무가 처리되었습니다.');await loadDashboard()}catch(e){toast(`처리 실패: ${e.code||e.message}`)}}))}

async function loadOrders(){state.orders=(await api('/api/orders')).items;$('#order-form button').disabled=!can('orders.create');$('#order-list').innerHTML=state.orders.length?state.orders.map(o=>{const next={NEW:'PICKING',PICKING:'SHIPPED',SHIPPED:'DELIVERED'}[o.status];return `<article class="record"><div><strong>${escapeHtml(o.id)} · ${escapeHtml(o.customer_name)}</strong><small>${formatMoney(o.total_cents)} · ${escapeHtml(o.status)} · v${o.version}</small></div><div class="actions">${next?`<button class="action primary-action" data-order-next="${escapeHtml(o.id)}" data-status="${next}" ${!can('orders.fulfill')?'disabled':''}>${next}</button>`:''}<button class="action" data-refund="${escapeHtml(o.id)}" ${!can('refunds.create')?'disabled':''}>환불 요청</button></div></article>`}).join(''):'<div class="empty">주문이 없습니다.</div>';$$('[data-order-next]').forEach(btn=>btn.onclick=async()=>{const order=state.orders.find(o=>o.id===btn.dataset.orderNext);try{await api(`/api/orders/${encodeURIComponent(order.id)}/status`,{method:'POST',body:{status:btn.dataset.status,expectedVersion:order.version}});toast('주문 상태를 변경했습니다.');await loadOrders()}catch(e){toast(`변경 실패: ${e.code||e.message}`)}});$$('[data-refund]').forEach(btn=>btn.onclick=async()=>{const order=state.orders.find(o=>o.id===btn.dataset.refund);const amount=prompt('환불 금액(원)',String(Math.round(order.total_cents/100)));if(!amount)return;const reason=prompt('환불 사유(4자 이상)','고객 요청에 따른 환불 검토');if(!reason)return;try{await api(`/api/orders/${encodeURIComponent(order.id)}/refunds`,{method:'POST',body:{amountCents:Math.round(Number(amount)*100),reason}});toast('환불 승인 업무를 생성했습니다.')}catch(e){toast(`환불 요청 실패: ${e.code||e.message}`)}})}
$('#order-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;message('order');const f=new FormData(form);try{await api('/api/orders',{method:'POST',body:{customerName:f.get('customerName'),totalCents:Math.round(Number(f.get('amount'))*100)}});form.reset();toast('주문을 등록했습니다.');await loadOrders()}catch(err){message('order',err.code||err.message)}});

async function loadDocuments(){state.documents=(await api('/api/documents')).items;$('#document-form button').disabled=!can('documents.write');$('#document-list').innerHTML=state.documents.length?state.documents.map(d=>{let action='';if(['DRAFT','NEEDS_CHANGES'].includes(d.status))action=`<button class="action primary-action" data-doc-submit="${escapeHtml(d.id)}" ${!can('documents.submit')?'disabled':''}>검수 요청</button>`;if(d.status==='SUBMITTED')action=`<button class="action primary-action" data-doc-review="${escapeHtml(d.id)}" ${!can('documents.review')?'disabled':''}>승인</button>`;if(d.status==='APPROVED'&&state.user.role==='ADMIN')action=`<button class="action" data-doc-archive="${escapeHtml(d.id)}">보관</button>`;return `<article class="record"><div><strong>${escapeHtml(d.title)}</strong><small>${escapeHtml(d.type)} · ${escapeHtml(d.status)} · v${d.version}</small></div><div class="actions">${action}</div></article>`}).join(''):'<div class="empty">문서가 없습니다.</div>';$$('[data-doc-submit]').forEach(btn=>btn.onclick=async()=>{const d=state.documents.find(x=>x.id===btn.dataset.docSubmit);try{await api(`/api/documents/${encodeURIComponent(d.id)}/submit`,{method:'POST',body:{expectedVersion:d.version}});toast('검수를 요청했습니다.');await loadDocuments()}catch(e){toast(e.code||e.message)}});$$('[data-doc-review]').forEach(btn=>btn.onclick=async()=>{const d=state.documents.find(x=>x.id===btn.dataset.docReview);const note=prompt('승인 근거(4자 이상)','원문과 입력값 대조 확인 완료');if(!note)return;try{await api(`/api/documents/${encodeURIComponent(d.id)}/review`,{method:'POST',body:{decision:'APPROVE',note,expectedVersion:d.version}});toast('문서를 승인했습니다.');await loadDocuments()}catch(e){toast(e.code||e.message)}});$$('[data-doc-archive]').forEach(btn=>btn.onclick=async()=>{const d=state.documents.find(x=>x.id===btn.dataset.docArchive);try{await api(`/api/documents/${encodeURIComponent(d.id)}/archive`,{method:'POST',body:{expectedVersion:d.version}});toast('문서를 보관했습니다.');await loadDocuments()}catch(e){toast(e.code||e.message)}})}
$('#document-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;message('document');const f=new FormData(form);try{await api('/api/documents',{method:'POST',body:{title:f.get('title'),type:f.get('type'),sourceText:f.get('sourceText')}});form.reset();toast('문서를 접수했습니다.');await loadDocuments()}catch(err){message('document',err.code||err.message)}});

async function loadSupport(){state.support=(await api('/api/support/tasks')).items;$('#support-form button').disabled=!can('support.create');$('#support-list').innerHTML=state.support.length?state.support.map(t=>{let actions='';if(['PENDING'].includes(t.status))actions=`<button class="action primary-action" data-generate="${escapeHtml(t.id)}" ${!can('support.generate')?'disabled':''}>AI 초안 생성</button>`;if(t.status==='NEEDS_REVIEW')actions=`<button class="action primary-action" data-support-approve="${escapeHtml(t.id)}" ${!can('support.review')?'disabled':''}>사람 승인</button>`;return `<article class="record"><div><strong>${escapeHtml(t.title)}</strong><small>${escapeHtml(t.status)} · v${t.version}${t.provider_id?` · ${escapeHtml(t.provider_id)}`:''}</small>${t.output?`<pre>${escapeHtml(t.output.answer||JSON.stringify(t.output))}</pre>`:''}</div><div class="actions">${actions}</div></article>`}).join(''):'<div class="empty">등록된 문의가 없습니다.</div>';$$('[data-generate]').forEach(btn=>btn.onclick=async()=>{const t=state.support.find(x=>x.id===btn.dataset.generate);btn.disabled=true;try{await api(`/api/support/tasks/${encodeURIComponent(t.id)}/generate`,{method:'POST',body:{expectedVersion:t.version}});toast('근거 기반 AI 초안을 생성했습니다.');await loadSupport()}catch(e){toast(`생성 실패: ${e.code||e.message}`)}finally{btn.disabled=false}});$$('[data-support-approve]').forEach(btn=>btn.onclick=async()=>{const t=state.support.find(x=>x.id===btn.dataset.supportApprove);const note=prompt('검토 근거(4자 이상)','근거자료와 답변 문구 확인 완료');if(!note)return;try{await api(`/api/support/tasks/${encodeURIComponent(t.id)}/review`,{method:'POST',body:{decision:'APPROVE',note,expectedVersion:t.version}});toast('사람 검토 후 승인했습니다.');await loadSupport()}catch(e){toast(e.code||e.message)}})}
$('#support-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;message('support');const f=new FormData(form);try{await api('/api/support/tasks',{method:'POST',body:{title:f.get('title'),content:f.get('content')}});form.reset();toast('고객 문의를 등록했습니다.');await loadSupport()}catch(err){message('support',err.code||err.message)}});

async function loadIntegrations(){const [c,j,r,d]=await Promise.all([api('/api/integrations/connections'),api('/api/integrations/jobs'),api('/api/integrations/runs'),api('/api/integrations/dead-letters')]);state.connections=c.items;state.jobs=j.items;state.runs=r.items;state.dead=d.items;$('#integration-metrics').innerHTML=[[c.items.length,'Connections'],[j.items.length,'Jobs'],[d.items.length,'Dead Letter']].map(([n,l])=>`<article><span>${l}</span><strong>${n}</strong><small>영속 DB 기준</small></article>`).join('');$('#connection-list').innerHTML=c.items.length?c.items.map(x=>`<article class="record"><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.kind)} · ${escapeHtml(x.state)}</small></div></article>`).join(''):'<div class="empty">Connection이 없습니다.</div>';$('#integration-list').innerHTML=[...j.items.map(x=>`<article class="record"><div><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.event_type)} · ${escapeHtml(x.status)} · retry ${x.max_retries}</small></div></article>`),...r.items.slice(0,10).map(x=>`<article class="record"><div><strong>${escapeHtml(x.id)}</strong><small>${escapeHtml(x.result)} · attempt ${x.attempt} · ${escapeHtml(x.detail)}</small></div></article>`)].join('')||'<div class="empty">Job/Run이 없습니다.</div>';$('#dead-list').innerHTML=d.items.length?d.items.map(x=>`<article class="record"><div><strong>${escapeHtml(x.id)}</strong><small>${escapeHtml(x.reason)}</small></div><div class="actions"><button class="action primary-action" data-dead-retry="${escapeHtml(x.id)}" ${!can('integrations.retry')?'disabled':''}>재처리</button></div></article>`).join(''):'<div class="empty">Dead Letter가 없습니다.</div>';$$('[data-dead-retry]').forEach(btn=>btn.onclick=async()=>{try{await api(`/api/integrations/dead-letters/${encodeURIComponent(btn.dataset.deadRetry)}/retry`,{method:'POST'});toast('재처리를 예약했습니다.');await loadIntegrations()}catch(e){toast(e.code||e.message)}})}

async function loadAudit(){if(!can('audit.read')&&state.user.role!=='ADMIN'){ $('#audit-list').innerHTML='<div class="empty">감사이력 조회 권한이 없습니다.</div>';return }const {items}=await api('/api/audit?limit=200');$('#audit-list').innerHTML=items.length?items.map(a=>`<article class="audit-row"><time>${escapeHtml(a.created_at)}</time><span>${escapeHtml(a.module)}</span><div><strong>${escapeHtml(a.action)} · ${escapeHtml(a.entity_id)}</strong><small>${escapeHtml(a.detail)}</small></div></article>`).join(''):'<div class="empty">감사이력이 없습니다.</div>'}

$('#login-form').addEventListener('submit',async e=>{e.preventDefault();const form=e.currentTarget;$('#login-message').textContent='';const f=new FormData(form);try{const result=await api('/api/auth/login',{method:'POST',body:{email:f.get('email'),password:f.get('password')}});state.user=result.user;state.csrf=result.csrfToken;sessionStorage.setItem('mono.csrf',state.csrf);form.reset();showApp()}catch(error){$('#login-message').textContent=error.code==='INVALID_CREDENTIALS'?'이메일 또는 비밀번호를 확인해 주세요.':`로그인 실패: ${error.code||error.message}`}});
$('#logout-btn').addEventListener('click',async()=>{try{await api('/api/auth/logout',{method:'POST'})}catch{}sessionStorage.removeItem('mono.csrf');state.csrf='';showLogin()});
$('#menu-btn').addEventListener('click',()=>$('#sidebar').classList.toggle('open'));
$$('.sidebar nav button').forEach(btn=>btn.addEventListener('click',()=>setView(btn.dataset.view)));
$('#work-filter').addEventListener('change',renderWork);$('#refresh-dashboard').onclick=loadDashboard;$('#refresh-integrations').onclick=loadIntegrations;$('#refresh-audit').onclick=loadAudit;

(async function boot(){if(!state.csrf){showLogin();return}try{const result=await api('/api/me');state.user=result.user;showApp()}catch{sessionStorage.removeItem('mono.csrf');state.csrf='';showLogin()}})();