import { publishContent, parseKeyValueText, extractTableRows, simulateAutomation } from './engine.mjs';
const $=s=>document.querySelector(s);const make=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
document.querySelectorAll('[data-tab]').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('[data-tab]').forEach(x=>x.classList.toggle('active',x===btn));document.querySelectorAll('.lab').forEach(x=>x.classList.toggle('active',x.id===btn.dataset.tab));}));
function resultTitle(target,ok,title,copy){target.replaceChildren();const head=make('div','result-head');head.append(make('span',ok?'result-ok':'result-fail',ok?'처리 완료':'확인 필요'),make('strong','',title));target.append(head,make('p','muted',copy));return target;}
$('#cms-run').addEventListener('click',()=>{const out=$('#cms-output');try{const result=publishContent({title:$('#cms-title').value,body:$('#cms-body').value});resultTitle(out,true,'게시할 수 있습니다.','제목과 본문의 필수 조건을 모두 확인했습니다.');const list=make('div','result-list');list.append(make('div','result-row',`게시 제목 · ${result.title}`),make('div','result-row','주소용 이름 · 자동 생성 완료'));out.append(list);}catch{resultTitle(out,false,'내용을 조금 더 채워주세요.','제목은 3자 이상, 본문은 20자 이상 입력해야 게시할 수 있습니다.');}});
$('#extract-run').addEventListener('click',()=>{const out=$('#extract-output');try{const values=parseKeyValueText($('#kv-source').value),rows=extractTableRows($('#csv-source').value);resultTitle(out,true,'값을 정리했습니다.',`문서에서 ${Object.keys(values).length}개 항목, 표에서 ${rows.length}개 행을 읽었습니다.`);const list=make('div','result-list');for(const [key,value] of Object.entries(values))list.append(make('div','result-row',`${key.replaceAll('_',' ')} · ${value}`));for(const row of rows.slice(0,4))list.append(make('div','result-row',Object.values(row).join(' · ')));out.append(list);}catch{resultTitle(out,false,'표 형식을 확인해 주세요.','첫 줄의 컬럼 수와 아래 데이터의 값 개수가 같은지 확인해 주세요.');}});
const plan=[{id:'open',type:'NAVIGATE',target:'https://example.com/form'},{id:'fill',type:'INPUT',target:'#name',value:'Demo User'},{id:'submit',type:'CLICK',target:'#submit'},{id:'assert',type:'ASSERT_TEXT',target:'#status',value:'Saved'}];const stepLabels={open:'입력 화면 열기',fill:'고객명 입력',submit:'저장 버튼 누르기',assert:'저장 완료 확인'};
$('#automation-run').addEventListener('click',()=>{const out=$('#automation-output'),result=simulateAutomation(plan,{failAt:$('#fail-step').value});resultTitle(out,result.status==='SUCCESS',result.status==='SUCCESS'?'반복작업을 끝까지 완료했습니다.':'중간 단계에서 멈췄습니다.',result.status==='SUCCESS'?`${result.completed}단계를 순서대로 처리했습니다.`:'실패한 단계부터 다시 확인할 수 있습니다.');const list=make('div','result-list');for(const event of result.events){const row=make('div','result-row');row.append(make('span','',stepLabels[event.stepId]??event.stepId),make('strong',event.status==='SUCCESS'?'ok-text':'fail-text',event.status==='SUCCESS'?'완료':'실패'));list.append(row);}out.append(list);});
$('#cms-run').click();$('#extract-run').click();$('#automation-run').click();
