import { mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import { DatabaseSync } from 'node:sqlite';
import { randomUUID } from 'node:crypto';
import { createStore as marketSeed, DomainError as MarketError } from '../../commerce-ops-console/server/store.mjs';
import { createStore as officeSeed, DomainError as OfficeError } from '../../document-intake-approval/server/store.mjs';
import { createStore as supportSeed, DomainError as SupportError } from '../../ai-workflow-review-desk/server/store.mjs';
import { createStore as dataSeed, ApiError as DataError, validateWebhookInput } from '../../integration-control-center/server/store.mjs';
import { assertExpectedVersion as assertOrderVersion, startPicking, markShipped, markDelivered, decideRefund, computeMetrics as marketMetrics, snapshotOrder } from '../../commerce-ops-console/engine.mjs';
import { assertExpectedVersion as assertDocVersion, reviewDocument, archiveDocument, computeMetrics as officeMetrics, snapshotDocument } from '../../document-intake-approval/engine.mjs';
import { TASK_STATUS, RUN_STATUS, applyHumanReview, nextTaskStatus, runGeneration, validateStructuredOutput } from '../../ai-workflow-review-desk/engine.mjs';

const clone=v=>structuredClone(v);const iso=()=>new Date().toISOString();
function dbFor(path){if(path!==':memory:')mkdirSync(dirname(path),{recursive:true});const db=new DatabaseSync(path);if(path!==':memory:')db.exec('PRAGMA journal_mode=WAL');db.exec('CREATE TABLE IF NOT EXISTS mono_module_state(module TEXT PRIMARY KEY,state_json TEXT NOT NULL,updated_at TEXT NOT NULL)');return db;}
function stateSlot(db,module,seed){const row=db.prepare('SELECT state_json FROM mono_module_state WHERE module=?').get(module);let state;if(row){try{state=JSON.parse(row.state_json);}catch{state=null;}}if(!state){state=seed();db.prepare('INSERT OR REPLACE INTO mono_module_state(module,state_json,updated_at) VALUES(?,?,?)').run(module,JSON.stringify(state),iso());}const save=()=>db.prepare('UPDATE mono_module_state SET state_json=?,updated_at=? WHERE module=?').run(JSON.stringify(state),iso(),module);return{get:()=>state,set:value=>{state=value;save();},save};}
function mapOrderError(error){const message=error instanceof Error?error.message:String(error);if(message.startsWith('STALE_ORDER_VERSION:'))return new MarketError(409,'STALE_ORDER',message);if(/expectedVersion/.test(message))return new MarketError(400,'EXPECTED_VERSION_REQUIRED',message);if(/decisionNote/.test(message))return new MarketError(400,'REFUND_DECISION_NOTE_REQUIRED',message);return new MarketError(409,'INVALID_ORDER_ACTION',message);}
function mapDocError(error){const message=error instanceof Error?error.message:String(error);if(message.startsWith('STALE_DOCUMENT_VERSION:'))return new OfficeError(409,'STALE_DOCUMENT',message);if(/expectedVersion/.test(message))return new OfficeError(400,'EXPECTED_VERSION_REQUIRED',message);return new OfficeError(409,'INVALID_DOCUMENT_ACTION',message);}

export function createPersistentModules(path=':memory:'){
  const db=dbFor(path);
  const mseed=marketSeed(),oseed=officeSeed(),sseed=supportSeed(),dseed=dataSeed();
  const marketSlot=stateSlot(db,'MARKET',()=>({orders:mseed.listOrders({}),refunds:mseed.listRefunds(),audits:mseed.listAudits().slice().reverse(),auditSeq:100}));
  const officeSlot=stateSlot(db,'OFFICE',()=>({docs:oseed.listDocuments({}),audits:oseed.listAudits().slice().reverse(),auditSeq:100}));
  const supportSlot=stateSlot(db,'SUPPORT',()=>({tasks:sseed.listTasks(),runs:sseed.listRuns().slice().reverse(),reviews:sseed.listReviews().slice().reverse(),runSeq:100,reviewSeq:100}));
  const dataSlot=stateSlot(db,'DATA_HUB',()=>({connections:dseed.listConnections(),jobs:dseed.listJobs(),runs:dseed.listRuns(100),webhookEvents:dseed.listWebhookEvents(100),deadLetters:dseed.listDeadLetters(100),dedup:{}}));

  const market={
    listOrders(filters={}){const q=String(filters.query||'').trim().toLowerCase();return marketSlot.get().orders.filter(o=>!q||[o.orderNo,o.customerName,o.email].some(v=>String(v).toLowerCase().includes(q))).map(snapshotOrder);},
    getOrder(id){const o=marketSlot.get().orders.find(x=>x.id===Number(id));if(!o)throw new MarketError(404,'ORDER_NOT_FOUND','order not found');return snapshotOrder(o);},
    listRefunds(status=''){return marketSlot.get().refunds.filter(r=>!status||r.status===status).map(clone);},
    listAudits(orderId=null){return marketSlot.get().audits.filter(a=>orderId===null||a.orderId===Number(orderId)).map(clone).reverse();},
    metrics(){const s=marketSlot.get();return marketMetrics(s.orders,s.refunds);},
    createOrder(input,actor='ops-user'){const base=marketSeed();const created=base.createOrder(input,actor);const s=marketSlot.get(),next={...created,id:Math.max(0,...s.orders.map(o=>Number(o.id)||0))+1};s.orders.push(next);s.audits.push({id:s.auditSeq++,orderId:next.id,actor,action:'CREATE',detail:`${next.orderNo} · ${next.total} ${next.currency}`,orderVersion:next.version,createdAt:iso()});marketSlot.save();return snapshotOrder(next);},
    mutate(id,input,action,fn,detail=''){const s=marketSlot.get(),idx=s.orders.findIndex(x=>x.id===Number(id));if(idx<0)throw new MarketError(404,'ORDER_NOT_FOUND','order not found');const current=s.orders[idx];try{assertOrderVersion(current,input.expectedVersion);}catch(e){throw mapOrderError(e);}let next;try{next=fn(clone(current),iso());}catch(e){throw mapOrderError(e);}s.orders[idx]=next;s.audits.push({id:s.auditSeq++,orderId:next.id,actor:String(input.actor||'ops-user'),action,detail:String(detail||''),orderVersion:next.version,createdAt:iso()});marketSlot.save();return snapshotOrder(next);},
    startPicking(id,input={}){return this.mutate(id,input,'START_PICKING',order=>startPicking(order,iso()));},
    ship(id,input={}){return this.mutate(id,input,'SHIP',order=>markShipped(order,input.trackingNo,iso()),input.trackingNo);},
    deliver(id,input={}){return this.mutate(id,input,'DELIVER',order=>markDelivered(order,iso()));},
    decideRefund(refundId,input={}){const s=marketSlot.get(),ridx=s.refunds.findIndex(r=>r.id===Number(refundId));if(ridx<0)throw new MarketError(404,'REFUND_NOT_FOUND','refund not found');const refund=s.refunds[ridx],oidx=s.orders.findIndex(o=>o.id===refund.orderId);if(oidx<0)throw new MarketError(404,'ORDER_NOT_FOUND','order not found');const order=s.orders[oidx];try{assertOrderVersion(order,input.expectedVersion);}catch(e){throw mapOrderError(e);}if(refund.requiresApproval&&String(input.role||'').toUpperCase()!=='ADMIN')throw new MarketError(403,'REFUND_APPROVAL_FORBIDDEN','ADMIN role is required');let result;try{result=decideRefund(clone(order),clone(refund),input,iso());}catch(e){throw mapOrderError(e);}s.orders[oidx]=result.order;s.refunds[ridx]=result.refund;s.audits.push({id:s.auditSeq++,orderId:order.id,actor:String(input.decidedBy||'ops-admin'),action:result.refund.status==='APPROVED'?'APPROVE_REFUND':'REJECT_REFUND',detail:result.refund.decisionNote||'',orderVersion:result.order.version,createdAt:iso()});marketSlot.save();return{order:snapshotOrder(result.order),refund:clone(result.refund)};}
  };

  const office={
    listDocuments(filters={}){const q=String(filters.query||'').trim().toLowerCase(),status=String(filters.status||''),type=String(filters.type||'');return officeSlot.get().docs.filter(d=>!q||[d.title,d.type,...Object.values(d.metadata||{})].some(v=>String(v).toLowerCase().includes(q))).filter(d=>!status||d.status===status).filter(d=>!type||d.type===type).map(snapshotDocument);},
    getDocument(id){const d=officeSlot.get().docs.find(x=>x.id===Number(id));if(!d)throw new OfficeError(404,'DOCUMENT_NOT_FOUND','document not found');return snapshotDocument(d);},
    metrics(){return officeMetrics(officeSlot.get().docs);},listAudits(documentId=null){return officeSlot.get().audits.filter(a=>documentId===null||a.documentId===Number(documentId)).map(clone).reverse();},
    review(id,input={}){const s=officeSlot.get(),idx=s.docs.findIndex(d=>d.id===Number(id));if(idx<0)throw new OfficeError(404,'DOCUMENT_NOT_FOUND','document not found');const current=s.docs[idx];try{assertDocVersion(current,input.expectedVersion);}catch(e){throw mapDocError(e);}const role=String(input.role||'').toUpperCase();if(!['REVIEWER','ADMIN'].includes(role))throw new OfficeError(403,'REVIEW_FORBIDDEN','REVIEWER or ADMIN role is required');let next;try{next=reviewDocument(clone(current),input,iso());}catch(e){throw mapDocError(e);}s.docs[idx]=next;s.audits.push({id:s.auditSeq++,documentId:next.id,actor:String(input.reviewer||'reviewer'),action:String(input.decision||'REVIEW'),detail:String(input.comment||''),documentVersion:next.version,createdAt:iso()});officeSlot.save();return snapshotDocument(next);},
    archive(id,input={}){const s=officeSlot.get(),idx=s.docs.findIndex(d=>d.id===Number(id));if(idx<0)throw new OfficeError(404,'DOCUMENT_NOT_FOUND','document not found');const current=s.docs[idx];try{assertDocVersion(current,input.expectedVersion);}catch(e){throw mapDocError(e);}if(String(input.role||'').toUpperCase()!=='ADMIN')throw new OfficeError(403,'ARCHIVE_FORBIDDEN','ADMIN role is required');let next;try{next=archiveDocument(clone(current),iso());}catch(e){throw mapDocError(e);}s.docs[idx]=next;s.audits.push({id:s.auditSeq++,documentId:next.id,actor:String(input.actor||'admin'),action:'ARCHIVE',detail:'',documentVersion:next.version,createdAt:iso()});officeSlot.save();return snapshotDocument(next);}
  };

  const support={
    listTasks(){return supportSlot.get().tasks.map(clone);},listRuns(){return supportSlot.get().runs.map(clone).reverse();},listReviews(){return supportSlot.get().reviews.map(clone).reverse();},
    generateTask(id,options={}){const s=supportSlot.get(),task=s.tasks.find(t=>t.id===Number(id));if(!task)throw new SupportError(404,'TASK_NOT_FOUND','task not found');if([TASK_STATUS.APPROVED,TASK_STATUS.REJECTED].includes(task.status))throw new SupportError(409,'TASK_FINALIZED','reviewed task cannot be regenerated');const run=runGeneration(task,options),timestamp=iso(),record={id:s.runSeq++,taskId:task.id,status:run.status,providerId:run.providerId,promptVersion:run.promptVersion,output:run.output,evaluation:run.evaluation,retrieval:run.retrieval,attempts:run.attempts,createdAt:timestamp};s.runs.push(record);task.version+=1;task.updatedAt=timestamp;task.retrieval=run.retrieval;if(run.status===RUN_STATUS.SUCCESS){task.output=run.output;task.evaluation=run.evaluation;task.status=nextTaskStatus(run);}else{task.output=null;task.evaluation=run.evaluation;task.status=TASK_STATUS.PENDING;}supportSlot.save();return{task:clone(task),run:clone(record)};},
    reviewTask(id,input={}){const s=supportSlot.get(),task=s.tasks.find(t=>t.id===Number(id));if(!task)throw new SupportError(404,'TASK_NOT_FOUND','task not found');const expected=Number(input.expectedVersion);if(!Number.isInteger(expected)||expected<1)throw new SupportError(400,'EXPECTED_VERSION_REQUIRED','expectedVersion must be a positive integer');if(task.version!==expected)throw new SupportError(409,'STALE_REVIEW',`task version changed from ${expected} to ${task.version}`);if(input.editedOutput&&!validateStructuredOutput(input.editedOutput))throw new SupportError(400,'INVALID_OUTPUT','editedOutput does not match schema');let reviewed;try{reviewed=applyHumanReview(task,String(input.decision||'').toUpperCase(),input.editedOutput??null);}catch(e){throw new SupportError(409,'INVALID_REVIEW_STATE',e instanceof Error?e.message:'invalid review state');}Object.assign(task,reviewed,{updatedAt:iso()});const evidenceIds=task.retrieval?.evidence?.map(item=>item.id)||[],review={id:s.reviewSeq++,taskId:task.id,decision:String(input.decision||'').toUpperCase(),reviewer:String(input.reviewer||'reviewer'),taskVersion:task.version,edited:Boolean(input.editedOutput),evidenceIds,evidenceCoverage:task.retrieval?.coverage||0,output:clone(task.output),createdAt:iso()};s.reviews.push(review);supportSlot.save();return{task:clone(task),review:clone(review)};}
  };

  function dataConnection(state,id){return state.connections.find(c=>c.id===id);}
  function dataJob(state,id){const job=state.jobs.find(j=>j.id===id);if(!job)throw new DataError(404,'JOB_NOT_FOUND',`Job not found: ${id}`);return job;}
  function dataRun(state,id){const run=state.runs.find(r=>r.id===id);if(!run)throw new DataError(404,'RUN_NOT_FOUND',`Run not found: ${id}`);return run;}
  function execute(state,job,context={}){if(job.status!=='ACTIVE')throw new DataError(409,'JOB_PAUSED','Paused jobs cannot run.');const source=dataConnection(state,job.source),target=dataConnection(state,job.target),failed=source?.state!=='ACTIVE'||target?.state!=='ACTIVE'||context.forceFailure===true,retryCount=Number(context.retryCount||0),dead=failed&&retryCount>=3,result=dead?'DEAD_LETTER':failed?'FAILED':'SUCCESS',at=iso(),run={id:`run-${randomUUID()}`,jobId:job.id,jobName:job.name,result,at,processed:failed?0:120,detail:failed?'Connection health check failed':`Completed with ${job.policy}`,replayed:false,trigger:context.trigger||'MANUAL',eventId:context.eventId||null,retryOf:context.retryOf||null,retryCount,deadLettered:dead};state.runs=[run,...state.runs].slice(0,300);job.lastRun=at;if(dead)state.deadLetters=[{id:`dead-${randomUUID()}`,runId:run.id,rootRunId:context.rootRunId||context.retryOf||run.id,jobId:job.id,jobName:job.name,reason:run.detail,at},...state.deadLetters].slice(0,100);return run;}
  const dataHub={
    listConnections(){return dataSlot.get().connections.map(clone);},listJobs(){return dataSlot.get().jobs.map(clone);},listRuns(limit=50){return dataSlot.get().runs.slice(0,Math.min(100,Math.max(1,Number(limit)||50))).map(clone);},listWebhookEvents(limit=50){return dataSlot.get().webhookEvents.slice(0,Math.min(100,Math.max(1,Number(limit)||50))).map(clone);},listDeadLetters(limit=50){return dataSlot.get().deadLetters.slice(0,Math.min(100,Math.max(1,Number(limit)||50))).map(clone);},
    runJob(id,idempotencyKey=''){const s=dataSlot.get(),job=dataJob(s,id),key=String(idempotencyKey||'').trim();if(key&&s.dedup[`run:${id}:${key}`])return{...clone(s.dedup[`run:${id}:${key}`]),replayed:true};const run=execute(s,job);if(key)s.dedup[`run:${id}:${key}`]=clone(run);dataSlot.save();return clone(run);},
    receiveWebhook(connectionId,input){const s=dataSlot.get(),connection=dataConnection(s,connectionId);if(!connection)throw new DataError(404,'CONNECTION_NOT_FOUND',`Connection not found: ${connectionId}`);if(connection.kind!=='Webhook')throw new DataError(409,'NOT_WEBHOOK_CONNECTION','Connection is not configured for webhooks.');if(connection.state!=='ACTIVE')throw new DataError(409,'CONNECTION_NOT_ACTIVE','Webhook connection is not active.');const value=validateWebhookInput(input),key=`${connectionId}:${value.eventId}`;if(s.dedup[`webhook:${key}`])return{...clone(s.dedup[`webhook:${key}`]),replayed:true};const job=s.jobs.find(j=>j.source===connectionId&&j.entity===value.entity&&j.schedule==='webhook');if(!job)throw new DataError(409,'NO_WEBHOOK_JOB','No active webhook job matches this event.');const run=execute(s,job,{trigger:'WEBHOOK',eventId:value.eventId,forceFailure:value.payload.simulateFailure===true}),event={id:`evt-${randomUUID()}`,connectionId,eventId:value.eventId,type:value.type,entity:value.entity,status:run.result==='SUCCESS'?'PROCESSED':'FAILED',runId:run.id,receivedAt:iso(),replayed:false};s.webhookEvents=[event,...s.webhookEvents].slice(0,200);s.dedup[`webhook:${key}`]=clone(event);dataSlot.save();return clone(event);},
    retryRun(id){const s=dataSlot.get(),previous=dataRun(s,id);if(previous.result!=='FAILED')throw new DataError(409,'RUN_NOT_RETRYABLE','Only FAILED runs can be retried.');if(previous.retryCount>=3)throw new DataError(409,'RETRY_LIMIT_REACHED','Retry limit reached.');const job=dataJob(s,previous.jobId),run=execute(s,job,{trigger:'RETRY',eventId:previous.eventId,retryOf:previous.id,retryCount:previous.retryCount+1,rootRunId:previous.retryOf||previous.id});dataSlot.save();return clone(run);}
  };
  return{market,office,support,dataHub,close(){db.close();}};
}
