import { createStore } from './server/store.mjs';
import { ACTION_LABELS, ROLE_LABELS, STATUS_LABELS, friendlyActor, friendlyError, uiLabel } from '../customer-ui.js';
const store=createStore();const state={selectedId:3,role:'STAFF'};const $=id=>document.getElementById(id);
const el={role:$('role'),search:$('search'),statusFilter:$('status-filter'),jobList:$('job-list'),empty:$('empty'),detail:$('detail'),jobTitle:$('job-title'),jobCopy:$('job-copy'),version:$('version'),status:$('status'),priority:$('priority'),agent:$('agent'),slot:$('slot'),actions:$('actions'),agentSelect:$('agent-select'),startAt:$('start-at'),endAt:$('end-at'),override:$('override'),schedule:$('schedule'),message:$('message'),agentBoard:$('agent-board'),auditList:$('audit-list'),mActive:$('m-active'),mScheduled:$('m-scheduled'),mDispatched:$('m-dispatched'),mOnsite:$('m-onsite'),mUrgent:$('m-urgent')};
const node=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};const badge=v=>node('span',`badge ${v}`,uiLabel(v));const actor=()=>state.role==='ADMIN'?'demo-admin':'dispatcher';
function job(){try{return store.getJob(state.selectedId);}catch{return null;}}function agentName(id){return store.listAgents().find(a=>a.id===id)?.name??'미배정';}function fmt(iso){return iso?new Date(iso).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'-';}function message(text,error=false){el.message.textContent=text;el.message.dataset.error=error?'true':'false';}
function metrics(){const m=store.metrics();el.mActive.textContent=m.active;el.mScheduled.textContent=m.scheduled;el.mDispatched.textContent=m.dispatched;el.mOnsite.textContent=m.onSite;el.mUrgent.textContent=m.urgent;}
function list(){const jobs=store.listJobs({query:el.search.value,status:el.statusFilter.value});el.jobList.replaceChildren();for(const j of jobs){const b=node('button',`job-card${j.id===state.selectedId?' active':''}`);b.type='button';const h=node('div','card-head');h.append(node('strong','',`#${j.id} ${j.customerName}`),badge(j.status));b.append(h,node('p','',j.summary),node('small','',`${uiLabel(j.priority)} · ${agentName(j.agentId)}${j.startAt?` · ${fmt(j.startAt)}`:' · 일정 미배정'}`));b.addEventListener('click',()=>{state.selectedId=j.id;message('');render();});el.jobList.append(b);}if(!jobs.length)el.jobList.append(node('div','empty compact','조건에 맞는 방문 요청이 없습니다.'));}
function run(action){const j=job();if(!j)return;try{const input={expectedVersion:j.version,actor:actor()};if(action==='DISPATCH')store.dispatch(j.id,input);else if(action==='ON_SITE')store.onSite(j.id,input);else if(action==='COMPLETE')store.complete(j.id,input);else if(action==='NO_SHOW')store.noShow(j.id,input);else if(action==='CANCEL'){if(!window.confirm('이 방문 작업을 취소하시겠습니까?'))return;store.cancel(j.id,input);}message(`${ACTION_LABELS[action]??'처리'}가 완료되었습니다.`);}catch(e){message(friendlyError(e),true);}render();}
function detail(){const j=job();el.empty.hidden=Boolean(j);el.detail.hidden=!j;if(!j)return;el.jobTitle.textContent=`#${j.id} · ${j.customerName}`;el.jobCopy.textContent=`${j.address} · ${j.summary}`;el.version.textContent='';el.status.textContent=uiLabel(j.status);el.priority.textContent=uiLabel(j.priority);el.agent.textContent=agentName(j.agentId);el.slot.textContent=j.startAt?`${fmt(j.startAt)} ~ ${fmt(j.endAt)}`:'아직 배정되지 않음';el.actions.replaceChildren();for(const action of j.allowedActions.filter(a=>!['SCHEDULE','RESCHEDULE','REASSIGN'].includes(a))){const b=node('button',`action ${action}`,ACTION_LABELS[action]??uiLabel(action));b.type='button';b.addEventListener('click',()=>run(action));el.actions.append(b);}if(!el.actions.children.length)el.actions.append(node('span','muted','현재 바로 처리할 작업이 없습니다.'));el.schedule.disabled=!j.allowedActions.some(a=>['SCHEDULE','RESCHEDULE','REASSIGN'].includes(a));el.schedule.textContent=j.status==='REQUESTED'?'일정 배정':'일정 변경';if(j.agentId)el.agentSelect.value=String(j.agentId);}
function agents(){const agents=store.listAgents(),jobs=store.listJobs();el.agentSelect.replaceChildren(...agents.map(a=>{const o=node('option','',`${a.name} · ${a.region}`);o.value=String(a.id);return o;}));const keep=job()?.agentId;if(keep)el.agentSelect.value=String(keep);el.agentBoard.replaceChildren();for(const a of agents){const card=node('article','agent-card');card.append(node('strong','',`${a.name} · ${a.region}`));const active=jobs.filter(j=>j.agentId===a.id&&['SCHEDULED','DISPATCHED','ON_SITE'].includes(j.status)).sort((x,y)=>String(x.startAt).localeCompare(String(y.startAt)));if(!active.length)card.append(node('p','muted','예정된 방문 없음'));for(const j of active)card.append(node('p','',`${fmt(j.startAt)} · #${j.id} ${j.customerName} · ${uiLabel(j.status)}`));el.agentBoard.append(card);}}
function audits(){el.auditList.replaceChildren();for(const a of store.listAudits().slice(0,20)){const r=node('article','audit');const h=node('div');h.append(node('strong','',`${ACTION_LABELS[a.action]??uiLabel(a.action)} · 작업 #${a.jobId}`),node('span','',friendlyActor(a.actor)));let detail=a.detail||'';for(const [key,label] of Object.entries(STATUS_LABELS))detail=detail.replaceAll(key,label);r.append(h,node('p','',detail||'상태 변경'));el.auditList.append(r);}}
function render(){metrics();list();detail();agents();audits();}
el.role.addEventListener('change',()=>{state.role=el.role.value;message(`${state.role==='ADMIN'?'관리자':'배차 담당자'} 화면으로 전환했습니다.`);render();});el.search.addEventListener('input',list);el.statusFilter.addEventListener('change',list);
el.schedule.addEventListener('click',()=>{const j=job();if(!j)return;try{if(!el.startAt.value||!el.endAt.value){message('방문 시작과 종료 시간을 입력해 주세요.',true);return;}const input={expectedVersion:j.version,agentId:Number(el.agentSelect.value),startAt:new Date(el.startAt.value).toISOString(),endAt:new Date(el.endAt.value).toISOString(),role:state.role,actor:actor(),overrideReason:el.override.value};if(j.status==='REQUESTED')store.schedule(j.id,input);else store.reschedule(j.id,input);message(j.status==='REQUESTED'?'방문 일정을 배정했습니다.':'방문 일정을 변경했습니다.');el.override.value='';}catch(e){message(friendlyError(e,'일정 정보를 다시 확인해 주세요.'),true);}render();});render();
