import { createStore } from './server/store.mjs';
const store=createStore();const state={selectedId:3,role:'STAFF'};const $=id=>document.getElementById(id);
const el={role:$('role'),search:$('search'),statusFilter:$('status-filter'),jobList:$('job-list'),empty:$('empty'),detail:$('detail'),jobTitle:$('job-title'),jobCopy:$('job-copy'),version:$('version'),status:$('status'),priority:$('priority'),agent:$('agent'),slot:$('slot'),actions:$('actions'),agentSelect:$('agent-select'),startAt:$('start-at'),endAt:$('end-at'),override:$('override'),schedule:$('schedule'),message:$('message'),agentBoard:$('agent-board'),auditList:$('audit-list'),mActive:$('m-active'),mScheduled:$('m-scheduled'),mDispatched:$('m-dispatched'),mOnsite:$('m-onsite'),mUrgent:$('m-urgent')};
const node=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};const badge=v=>node('span',`badge ${v}`,v);const actor=()=>state.role==='ADMIN'?'demo-admin':'dispatcher';
function job(){try{return store.getJob(state.selectedId);}catch{return null;}}function agentName(id){return store.listAgents().find(a=>a.id===id)?.name??'Unassigned';}function fmt(iso){return iso?new Date(iso).toLocaleString('ko-KR',{month:'2-digit',day:'2-digit',hour:'2-digit',minute:'2-digit'}):'-';}
function message(text,error=false){el.message.textContent=text;el.message.dataset.error=error?'true':'false';}
function metrics(){const m=store.metrics();el.mActive.textContent=m.active;el.mScheduled.textContent=m.scheduled;el.mDispatched.textContent=m.dispatched;el.mOnsite.textContent=m.onSite;el.mUrgent.textContent=m.urgent;}
function list(){const jobs=store.listJobs({query:el.search.value,status:el.statusFilter.value});el.jobList.replaceChildren();for(const j of jobs){const b=node('button',`job-card${j.id===state.selectedId?' active':''}`);b.type='button';const h=node('div','card-head');h.append(node('strong','',`#${j.id} ${j.customerName}`),badge(j.status));const p=node('p','',j.summary);const meta=node('small','',`${j.priority} · ${agentName(j.agentId)} · v${j.version}`);b.append(h,p,meta);b.addEventListener('click',()=>{state.selectedId=j.id;message('');render();});el.jobList.append(b);}if(!jobs.length)el.jobList.append(node('div','empty compact','조건에 맞는 작업이 없습니다.'));}
function run(action){const j=job();if(!j)return;try{const input={expectedVersion:j.version,actor:actor()};if(action==='DISPATCH')store.dispatch(j.id,input);else if(action==='ON_SITE')store.onSite(j.id,input);else if(action==='COMPLETE')store.complete(j.id,input);else if(action==='NO_SHOW')store.noShow(j.id,input);else if(action==='CANCEL'){if(!window.confirm('이 작업을 취소하시겠습니까?'))return;store.cancel(j.id,input);}message(`${action} 처리 완료`);}catch(e){message(e instanceof Error?e.message:'처리 실패',true);}render();}
function detail(){const j=job();el.empty.hidden=Boolean(j);el.detail.hidden=!j;if(!j)return;el.jobTitle.textContent=`#${j.id} · ${j.customerName}`;el.jobCopy.textContent=`${j.address} · ${j.summary}`;el.version.textContent=`VERSION ${j.version}`;el.status.textContent=j.status;el.priority.textContent=j.priority;el.agent.textContent=agentName(j.agentId);el.slot.textContent=j.startAt?`${fmt(j.startAt)} → ${fmt(j.endAt)}`:'미배정';el.actions.replaceChildren();for(const action of j.allowedActions.filter(a=>!['SCHEDULE','RESCHEDULE','REASSIGN'].includes(a))){const b=node('button',`action ${action}`,({DISPATCH:'Dispatch',ON_SITE:'On Site',COMPLETE:'Complete',NO_SHOW:'No-show',CANCEL:'Cancel'})[action]??action);b.type='button';b.addEventListener('click',()=>run(action));el.actions.append(b);}el.schedule.disabled=!j.allowedActions.some(a=>['SCHEDULE','RESCHEDULE','REASSIGN'].includes(a));el.schedule.textContent=j.status==='REQUESTED'?'일정 배정':'일정 변경';if(j.agentId)el.agentSelect.value=String(j.agentId);}
function agents(){const agents=store.listAgents(),jobs=store.listJobs();el.agentSelect.replaceChildren(...agents.map(a=>{const o=node('option','',`${a.name} · ${a.region}`);o.value=String(a.id);return o;}));const keep=job()?.agentId;if(keep)el.agentSelect.value=String(keep);el.agentBoard.replaceChildren();for(const a of agents){const card=node('article','agent-card');card.append(node('strong','',`${a.name} · ${a.region}`));const active=jobs.filter(j=>j.agentId===a.id&&['SCHEDULED','DISPATCHED','ON_SITE'].includes(j.status)).sort((x,y)=>String(x.startAt).localeCompare(String(y.startAt)));if(!active.length)card.append(node('p','muted','활성 일정 없음'));for(const j of active)card.append(node('p','',`${fmt(j.startAt)} · #${j.id} ${j.customerName} · ${j.status}`));el.agentBoard.append(card);}}
function audits(){el.auditList.replaceChildren();for(const a of store.listAudits().slice(0,20)){const r=node('article','audit');const h=node('div');h.append(node('strong','',`${a.action} · Job #${a.jobId}`),node('span','',`v${a.jobVersion}`));r.append(h,node('p','',`${a.actor}${a.detail?` · ${a.detail}`:''}`));el.auditList.append(r);}}
function render(){metrics();list();detail();agents();audits();}
el.role.addEventListener('change',()=>{state.role=el.role.value;message(`Demo role: ${state.role}`);render();});el.search.addEventListener('input',list);el.statusFilter.addEventListener('change',list);
el.schedule.addEventListener('click',()=>{const j=job();if(!j)return;try{const input={expectedVersion:j.version,agentId:Number(el.agentSelect.value),startAt:new Date(el.startAt.value).toISOString(),endAt:new Date(el.endAt.value).toISOString(),role:state.role,actor:actor(),overrideReason:el.override.value};if(j.status==='REQUESTED')store.schedule(j.id,input);else store.reschedule(j.id,input);message(j.status==='REQUESTED'?'일정 배정 완료':'일정 변경 완료');el.override.value='';}catch(e){message(e instanceof Error?e.message:'일정 처리 실패',true);}render();});render();
