import { assertExpectedVersion, applyExtraction, archiveDocument, computeMetrics, createDocument, reviewDocument, snapshotDocument, submitDocument, updateDocument } from '../engine.mjs';
export class DomainError extends Error{constructor(statusCode,code,message){super(message);this.name='DomainError';this.statusCode=statusCode;this.code=code;}}
const clone=v=>structuredClone(v);const now=()=>new Date().toISOString();
function mapError(e){const m=e instanceof Error?e.message:String(e);if(m.startsWith('STALE_DOCUMENT_VERSION:'))return new DomainError(409,'STALE_DOCUMENT',m);if(m==='CHECKLIST_INCOMPLETE')return new DomainError(409,'CHECKLIST_INCOMPLETE','required metadata is incomplete');if(/expectedVersion/.test(m))return new DomainError(400,'EXPECTED_VERSION_REQUIRED',m);return new DomainError(409,'INVALID_DOCUMENT_ACTION',m);}
const roleOf=input=>String(input?.role||'').trim().toUpperCase();
function requireSubmitter(input){if(roleOf(input)!=='SUBMITTER')throw new DomainError(403,'AUTHOR_FORBIDDEN','FORBIDDEN: SUBMITTER role is required');}
export function createStore(){const seeded='2026-09-06T00:00:00.000Z';const state={docSeq:5,auditSeq:7,docs:[
{id:1,type:'INVOICE',title:'9월 공급사 인보이스',status:'DRAFT',metadata:{documentNo:'INV-2026-0901',party:'Alpha Supply'},sourceText:'documentNo: INV-2026-0901\nparty: Alpha Supply\namount: 125000',version:1,reviewComment:null,reviewer:null,createdAt:seeded,updatedAt:seeded},
{id:2,type:'APPLICATION',title:'파트너 입점 신청서',status:'SUBMITTED',metadata:{applicantName:'Beta Partner',email:'contact@beta.example'},sourceText:'applicantName: Beta Partner\nemail: contact@beta.example',version:2,reviewComment:null,reviewer:null,createdAt:seeded,updatedAt:seeded},
{id:3,type:'CONTRACT',title:'서비스 계약 검토',status:'NEEDS_CHANGES',metadata:{documentNo:'CTR-2609',counterparty:'Gamma Co'},sourceText:'documentNo: CTR-2609\ncounterparty: Gamma Co\neffectiveDate: 2026-09-15',version:3,reviewComment:'계약 적용일을 확인해 주세요.',reviewer:'demo-reviewer',createdAt:seeded,updatedAt:seeded},
{id:4,type:'INVOICE',title:'승인 완료 인보이스',status:'APPROVED',metadata:{documentNo:'INV-APPROVED',party:'Delta Works',amount:'98000'},sourceText:'documentNo: INV-APPROVED\nparty: Delta Works\namount: 98000',version:3,reviewComment:'금액과 거래처 확인 완료',reviewer:'demo-reviewer',createdAt:seeded,updatedAt:seeded}
],audits:[
{id:1,documentId:2,actor:'submitter',action:'SUBMIT',detail:'',documentVersion:2,createdAt:seeded},{id:2,documentId:3,actor:'submitter',action:'SUBMIT',detail:'',documentVersion:2,createdAt:seeded},{id:3,documentId:3,actor:'demo-reviewer',action:'NEEDS_CHANGES',detail:'계약 적용일을 확인해 주세요.',documentVersion:3,createdAt:seeded},{id:4,documentId:4,actor:'submitter',action:'SUBMIT',detail:'',documentVersion:2,createdAt:seeded},{id:5,documentId:4,actor:'demo-reviewer',action:'APPROVE',detail:'금액과 거래처 확인 완료',documentVersion:3,createdAt:seeded},{id:6,documentId:1,actor:'system',action:'CREATE',detail:'INVOICE · 9월 공급사 인보이스',documentVersion:1,createdAt:seeded}]};
const find=id=>state.docs.find(d=>d.id===Number(id));const requireDoc=id=>{const d=find(id);if(!d)throw new DomainError(404,'DOCUMENT_NOT_FOUND','document not found');return d;};
const audit=(d,action,actor,detail='')=>state.audits.push({id:state.auditSeq++,documentId:d.id,actor:String(actor||'user').slice(0,80),action,detail:String(detail||'').slice(0,500),documentVersion:d.version,createdAt:now()});
const replace=d=>{state.docs[state.docs.findIndex(x=>x.id===d.id)]=d;return d;};const version=(d,v)=>{try{assertExpectedVersion(d,v);}catch(e){throw mapError(e);}};
return{
 listDocuments(filters={}){const q=String(filters.query||'').trim().toLowerCase(),status=String(filters.status||''),type=String(filters.type||'');return state.docs.filter(d=>!q||[d.title,d.type,...Object.values(d.metadata)].some(v=>String(v).toLowerCase().includes(q))).filter(d=>!status||d.status===status).filter(d=>!type||d.type===type).map(snapshotDocument);},getDocument(id){return snapshotDocument(requireDoc(id));},metrics(){return computeMetrics(state.docs);},listAudits(documentId=null){return state.audits.filter(a=>documentId===null||a.documentId===Number(documentId)).map(clone).reverse();},
 createDocument(input={}){requireSubmitter(input);let d;try{d=createDocument(input,{id:state.docSeq++,createdAt:now()});}catch(e){throw new DomainError(400,'INVALID_DOCUMENT',e instanceof Error?e.message:'invalid document');}state.docs.push(d);audit(d,'CREATE',input.actor,`${d.type} · ${d.title}`);return snapshotDocument(d);},
 update(id,input={}){requireSubmitter(input);const d=requireDoc(id);version(d,input.expectedVersion);let next;try{next=updateDocument(clone(d),input,now());}catch(e){throw mapError(e);}replace(next);audit(next,'EDIT',input.actor,'metadata/source updated');return snapshotDocument(next);},
 extract(id,input={}){requireSubmitter(input);const d=requireDoc(id);version(d,input.expectedVersion);let next;try{next=applyExtraction(clone(d),now());}catch(e){throw mapError(e);}replace(next);audit(next,'EXTRACT',input.actor,'deterministic key:value extraction');return snapshotDocument(next);},
 submit(id,input={}){requireSubmitter(input);const d=requireDoc(id);version(d,input.expectedVersion);let next;try{next=submitDocument(clone(d),now());}catch(e){throw mapError(e);}replace(next);audit(next,'SUBMIT',input.actor,'checklist validated');return snapshotDocument(next);},
 review(id,input={}){const d=requireDoc(id);version(d,input.expectedVersion);const role=roleOf(input);if(!['REVIEWER','ADMIN'].includes(role))throw new DomainError(403,'REVIEW_FORBIDDEN','FORBIDDEN: REVIEWER or ADMIN role is required');let next;try{next=reviewDocument(clone(d),input,now());}catch(e){throw mapError(e);}replace(next);audit(next,input.decision,String(input.reviewer||'reviewer'),input.comment);return snapshotDocument(next);},
 archive(id,input={}){const d=requireDoc(id);version(d,input.expectedVersion);if(roleOf(input)!=='ADMIN')throw new DomainError(403,'ARCHIVE_FORBIDDEN','FORBIDDEN: ADMIN role is required');let next;try{next=archiveDocument(clone(d),now());}catch(e){throw mapError(e);}replace(next);audit(next,'ARCHIVE',input.actor||'admin','finalized document archived');return snapshotDocument(next);}
};}
