(()=>{
  const main=document.querySelector('main');if(!main)return;
  const page=document.querySelector('.hero.hero-100')?'home':document.title.startsWith('서비스 |')?'services':document.title.startsWith('유지보수 상담 |')?'contact':'other';
  if(page==='other')return;
  if(main.querySelector('[data-commercial-scope-static]'))return;
  const section=document.createElement('section');section.className='commercial-scope';
  section.innerHTML=`<div class="shell"><div class="section-head section-head-100"><div><span class="korean-kicker">이용·계약 기준</span><h2>서비스를 시작하기 전에<br>지원 범위와 운영 기준을 먼저 맞춥니다.</h2></div><p>장비·지역·부품·현장조건을 확인한 뒤 정기관리, 건별 현장지원 또는 설치·이전 중 실제 필요한 범위를 확정합니다.</p></div><div class="scope-contract-grid"><article><span>01 · 지원 범위</span><h3>장비·지역·기술 확인</h3><p>장비 종류와 모델, 방문지역, 기술지원 가능 범위, 부품·제조사 정책을 확인한 뒤 지원 가능 여부를 안내합니다.</p></article><article><span>02 · 일정 기준</span><h3>업무 영향과 기사 일정</h3><p>모든 요청에 같은 시간을 약속하지 않습니다. 업무 중단 정도, 대체 장비, 지역, 기사 일정과 부품 상황을 확인해 방문 일정을 합의합니다.</p></article><article><span>03 · 작업 기준</span><h3>현장 확인과 완료 기준</h3><p>증상·원인·조치·정상 작동 여부를 확인하고, 현장에서 끝나지 않으면 부품·재방문·추가점검을 후속작업으로 구분합니다.</p></article><article><span>04 · 이력 관리</span><h3>다음 판단에 남는 기록</h3><p>접수·방문·조치·후속 요청을 같은 흐름으로 남겨 반복 장애와 다음 점검에서 이전 기록을 다시 확인할 수 있게 합니다.</p></article></div><div class="engagement-compare"><article><strong>정기 예방관리</strong><ul><li>중요 장비와 점검 주기 협의</li><li>반복 증상·소모품·주의항목 기록</li><li>다음 점검과 후속작업 연결</li></ul></article><article><strong>필요 시 현장지원</strong><ul><li>고장·장애 발생 시 건별 접수</li><li>업무 영향과 방문 가능시간 확인</li><li>현장 작업 후 결과와 남은 일 안내</li></ul></article><article><strong>설치·이전 작업</strong><ul><li>반입동선·전원·네트워크 사전 확인</li><li>설치 순서와 초기 가동 범위 합의</li><li>완료 확인과 남은 작업 정리</li></ul></article></div><div class="commercial-boundary"><strong>계약 전 확인:</strong> 실제 응답시간·방문시간·지원지역·대상 장비·부품비·정기점검 주기 등은 고객 환경을 확인한 뒤 계약 또는 작업 범위에 명시합니다. 확인되지 않은 응답시간이나 지원범위를 임의로 약속하지 않습니다.</div></div>`;
  const target=[...main.querySelectorAll('.cta')].at(-1);(target||main.lastElementChild)?.before(section);
})();
