import { uiLabel } from '../customer-ui.js';
const STORAGE_JOBS='icc-v12-jobs',STORAGE_RUNS='icc-v12-runs';
const initialConnections=[
{id:'crm-demo',name:'고객관리 프로그램',kind:'온라인 연결',state:'ACTIVE'},
{id:'erp-demo',name:'사내 업무관리 프로그램',kind:'온라인 연결',state:'ACTIVE'},
{id:'billing-demo',name:'결제 서비스',kind:'자동 알림',state:'PAUSED'},
{id:'warehouse-demo',name:'재고관리 프로그램',kind:'온라인 연결',state:'ERROR'},
{id:'sheet-demo',name:'업로드 파일',kind:'파일',state:'ACTIVE'},
{id:'analytics-demo',name:'분석 저장소',kind:'자동 저장',state:'ACTIVE'}
];
let connections=initialConnections.map(x=>({...x}));
const allowedEntities=new Set(['customers','orders','inventory','invoices']),allowedSchedules=new Set(['manual','hourly','daily']),allowedPolicies=new Set(['retry-3','stop','skip-row']);
const defaultJobs=[
{id:'job-customer-master',name:'고객정보 정기 전달',source:'crm-demo',target:'erp-demo',entity:'customers',schedule:'hourly',policy:'retry-3',status:'ACTIVE',lastRun:null},
{id:'job-order-export',name:'주문 분석자료 보내기',source:'erp-demo',target:'analytics-demo',entity:'orders',schedule:'daily',policy:'skip-row',status:'ACTIVE',lastRun:null},
{id:'job-stock-sync',name:'재고 수량 전달',source:'warehouse-demo',target:'erp-demo',entity:'inventory',schedule:'manual',policy:'stop',status:'ACTIVE',lastRun:null}
];
const $=id=>document.getElementById(id),el={connections:$('connectionList'),jobs:$('jobTable'),history:$('historyList'),flow:$('workflowPreview'),form:$('jobForm'),name:$('jobName'),source:$('jobSource'),target:$('jobTarget'),entity:$('jobEntity'),schedule:$('jobSchedule'),policy:$('jobPolicy'),formStatus:$('formStatus'),metricConnections:$('metricConnections'),metricActive:$('metricActive'),metricFailed:$('metricFailed'),metricRuns:$('metricRuns')};
const entityLabel={customers:'고객',orders:'주문',inventory:'재고',invoices:'청구서'},scheduleLabel={manual:'필요할 때 직접',hourly:'매시간',daily:'매일'},policyLabel={'retry-3':'최대 3회 다시 시도',stop:'오류가 생기면 중단','skip-row':'문제 행만 제외'};
function safeText(v,max=120){return typeof v==='string'?v.trim().slice(0,max):'';}function connectionIds(){return new Set(connections.map(x=>x.id));}
function sanitizeJob(v){if(!v||typeof v!=='object')return null;const id=safeText(v.id,100),name=safeText(v.name,80),source=safeText(v.source,60),target=safeText(v.target,60),entity=safeText(v.entity,40),schedule=safeText(v.schedule,40),policy=safeText(v.policy,40),status=v.status==='PAUSED'?'PAUSED':'ACTIVE',lastRun=typeof v.lastRun==='string'?v.lastRun.slice(0,40):null;if(!id||!name||source===target||!connectionIds().has(source)||!connectionIds().has(target)||!allowedEntities.has(entity)||!allowedSchedules.has(schedule)||!allowedPolicies.has(policy))return null;return{id,name,source,target,entity,schedule,policy,status,lastRun};}
function sanitizeRun(v){if(!v||typeof v!=='object')return null;const id=safeText(v.id,100),jobId=safeText(v.jobId,100),jobName=safeText(v.jobName,80),result=v.result==='FAILED'?'FAILED':v.result==='SUCCESS'?'SUCCESS':null,at=typeof v.at==='string'?v.at.slice(0,40):'',processed=Number.isInteger(v.processed)&&v.processed>=0&&v.processed<=1000000?v.processed:0,detail=safeText(v.detail,180);if(!id||!jobId||!jobName||!result||!at)return null;return{id,jobId,jobName,result,at,processed,detail};}
function loadArray(key,sanitizer,fallback=[]){try{const parsed=JSON.parse(localStorage.getItem(key)||'[]');if(!Array.isArray(parsed))return fallback;const clean=parsed.map(sanitizer).filter(Boolean);return clean.length?clean:fallback;}catch{return fallback;}}
let jobs=loadArray(STORAGE_JOBS,sanitizeJob,defaultJobs.map(x=>({...x}))),runs=loadArray(STORAGE_RUNS,sanitizeRun,[]);function persist(){localStorage.setItem(STORAGE_JOBS,JSON.stringify(jobs));localStorage.setItem(STORAGE_RUNS,JSON.stringify(runs.slice(0,80)));}
const connection=id=>connections.find(x=>x.id===id),connectionName=id=>connection(id)?.name||id,connectionState=id=>connection(id)?.state||'ERROR';
const make=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};function button(label,cls,fn){const b=make('button',cls,label);b.type='button';b.addEventListener('click',fn);return b;}function option(value,label){const o=document.createElement('option');o.value=value;o.textContent=label;return o;}
function flowNode(kicker,title,detail,issue=false){const card=make('article',`flow-node${issue?' issue':''}`);card.append(make('small','',kicker),make('strong','',title),make('span','',detail));return card;}
function renderFlow(){const fallback=jobs[0]??defaultJobs[0],sourceId=el.source.value||fallback.source,targetId=el.target.value||fallback.target,entity=el.entity.value||fallback.entity,schedule=el.schedule.value||fallback.schedule,source=connection(sourceId),target=connection(targetId);el.flow.replaceChildren(flowNode('가져오기',source?.name||'출발 프로그램 선택',source?uiLabel(source.state):'프로그램을 선택해 주세요.',source?.state==='ERROR'),make('span','flow-arrow','→'),make('span','flow-data',entityLabel[entity]??'옮길 데이터'),make('span','flow-arrow','→'),flowNode('보내기',target?.name||'도착 프로그램 선택',target?`${uiLabel(target.state)} · ${scheduleLabel[schedule]}`:'프로그램을 선택해 주세요.',target?.state==='ERROR'));}
function renderConnections(){const fragment=document.createDocumentFragment();for(const c of connections){const card=make('article','connection');const info=make('div','connection-copy');info.append(make('strong','',c.name),make('span','',c.kind));const state=make('span',`state state-${c.state.toLowerCase()}`,uiLabel(c.state));card.append(info,state);if(c.state!=='ACTIVE')card.append(button(c.state==='PAUSED'?'연결 재개':'연결 정상화','secondary',()=>recoverConnection(c.id)));fragment.append(card);}el.connections.replaceChildren(fragment);}
function renderConnectionSelects(){const sourceValue=el.source.value,targetValue=el.target.value,usable=connections.filter(x=>x.state!=='ERROR');el.source.replaceChildren(option('','가져올 프로그램 선택'),...usable.map(x=>option(x.id,x.name)));el.target.replaceChildren(option('','보낼 프로그램 선택'),...usable.map(x=>option(x.id,x.name)));if(usable.some(x=>x.id===sourceValue))el.source.value=sourceValue;if(usable.some(x=>x.id===targetValue))el.target.value=targetValue;}
function statusNode(status){return make('span',`job-status job-${status.toLowerCase()}`,uiLabel(status));}
function renderJobs(){const fragment=document.createDocumentFragment();for(const job of jobs){const row=document.createElement('tr');row.tabIndex=0;row.title='클릭하면 위 이동 흐름에서 이 작업을 미리 봅니다.';row.addEventListener('click',event=>{if(event.target.closest('button'))return;el.source.value=job.source;el.target.value=job.target;el.entity.value=job.entity;el.schedule.value=job.schedule;el.policy.value=job.policy;el.name.value=job.name;renderFlow();document.querySelector('.flow-panel')?.scrollIntoView({behavior:'smooth',block:'start'});});const name=document.createElement('td');name.append(make('strong','',job.name));const flow=make('td','',`${connectionName(job.source)} → ${connectionName(job.target)}`),entity=make('td','',entityLabel[job.entity]??job.entity),schedule=make('td','',scheduleLabel[job.schedule]??job.schedule),policy=make('td','',policyLabel[job.policy]??job.policy),status=document.createElement('td');status.append(statusNode(job.status));const last=make('td','',job.lastRun?new Date(job.lastRun).toLocaleString('ko-KR'):'아직 실행 전'),actions=document.createElement('td'),group=make('div','action-group');group.append(button('실행','run',()=>runJob(job.id)),button(job.status==='ACTIVE'?'일시정지':'다시 사용','secondary',()=>toggleJob(job.id)));actions.append(group);row.append(name,flow,entity,schedule,policy,status,last,actions);fragment.append(row);}el.jobs.replaceChildren(fragment);}
function runDetail(run){if(run.result==='SUCCESS')return `${run.processed.toLocaleString()}건 처리 완료`;if(run.detail==='Connection is paused')return '연결이 일시정지되어 실행하지 못했습니다.';return '연결 상태를 확인해야 합니다.';}
function renderHistory(){if(!runs.length){el.history.replaceChildren(make('p','form-status','아직 실행 이력이 없습니다.'));return;}const fragment=document.createDocumentFragment();for(const run of runs.slice(0,20)){const row=make('article',`history ${run.result==='FAILED'?'failed':''}`),dot=make('span','dot'),body=make('div',''),title=make('strong','',`${run.jobName} · ${uiLabel(run.result)}`),detail=make('span','',runDetail(run)),time=make('time','',new Date(run.at).toLocaleString('ko-KR'));body.append(title,detail);row.append(dot,body,time);if(run.result==='FAILED')row.append(button('다시 실행','secondary',()=>runJob(run.jobId)));fragment.append(row);}el.history.replaceChildren(fragment);}
function renderMetrics(){el.metricConnections.textContent=String(connections.length);el.metricActive.textContent=String(jobs.filter(j=>j.status==='ACTIVE').length);el.metricFailed.textContent=String(runs.filter(r=>r.result==='FAILED').length);el.metricRuns.textContent=String(runs.length);}
function render(){renderConnections();renderConnectionSelects();renderJobs();renderHistory();renderMetrics();renderFlow();}
function id(prefix){return`${prefix}-${typeof crypto.randomUUID==='function'?crypto.randomUUID():`${Date.now()}-${Math.random().toString(16).slice(2)}`}`;}
function recoverConnection(connectionId){connections=connections.map(c=>c.id===connectionId?{...c,state:'ACTIVE'}:c);el.formStatus.textContent=`${connectionName(connectionId)} 연결을 정상화했습니다. 실패한 작업을 다시 실행해보세요.`;render();}
function toggleJob(jobId){jobs=jobs.map(j=>j.id===jobId?{...j,status:j.status==='ACTIVE'?'PAUSED':'ACTIVE'}:j);persist();render();}
function runJob(jobId){const job=jobs.find(x=>x.id===jobId);if(!job)return;if(job.status!=='ACTIVE'){el.formStatus.textContent='일시정지된 작업입니다. 먼저 다시 사용으로 바꿔주세요.';return;}const now=new Date().toISOString(),blocked=connectionState(job.source)==='ERROR'||connectionState(job.target)==='ERROR',paused=connectionState(job.source)==='PAUSED'||connectionState(job.target)==='PAUSED',result=blocked||paused?'FAILED':'SUCCESS',seed=[...job.name].reduce((s,c)=>s+c.charCodeAt(0),0),processed=result==='SUCCESS'?80+(seed%421):0,detail=result==='SUCCESS'?'Completed':paused?'Connection is paused':'Connection health check failed';runs=[{id:id('run'),jobId:job.id,jobName:job.name,result,at:now,processed,detail},...runs].slice(0,80);jobs=jobs.map(x=>x.id===jobId?{...x,lastRun:now}:x);persist();render();el.formStatus.textContent=result==='SUCCESS'?'데이터 전달이 완료되었습니다.':'실행에 실패했습니다. 위 연결 상태에서 문제가 있는 프로그램을 정상화해 주세요.';}
for(const input of [el.source,el.target,el.entity,el.schedule])input.addEventListener('change',renderFlow);
el.form.addEventListener('submit',event=>{event.preventDefault();const name=safeText(el.name.value,80),source=el.source.value,target=el.target.value,entity=el.entity.value,schedule=el.schedule.value,policy=el.policy.value;if(!name||!connectionIds().has(source)||!connectionIds().has(target)||source===target){el.formStatus.textContent='작업 이름과 서로 다른 두 프로그램을 선택해 주세요.';return;}if(!allowedEntities.has(entity)||!allowedSchedules.has(schedule)||!allowedPolicies.has(policy)){el.formStatus.textContent='작업 설정을 다시 확인해 주세요.';return;}jobs=[{id:id('job'),name,source,target,entity,schedule,policy,status:'ACTIVE',lastRun:null},...jobs].slice(0,40);el.form.reset();el.formStatus.textContent='새 데이터 전달 작업을 추가했습니다.';persist();render();});
$('resetDemo').addEventListener('click',()=>{connections=initialConnections.map(x=>({...x}));jobs=defaultJobs.map(x=>({...x}));runs=[];persist();el.form.reset();render();el.formStatus.textContent='가상 데이터를 처음 상태로 되돌렸습니다.';});$('clearHistory').addEventListener('click',()=>{runs=[];persist();render();});render();
