const MODULE_URLS={MARKET:'../commerce-ops-console/',OFFICE:'../document-intake-approval/',SUPPORT:'../ai-workflow-review-desk/',DATA_HUB:'../integration-control-center/'};
const ROLE_CAPS={OPERATOR:['orders.read','orders.fulfill','support.read','integrations.read'],REVIEWER:['orders.read','documents.read','documents.review','support.read','support.review'],MANAGER:['orders.read','orders.fulfill','refunds.approve','documents.read','documents.review','support.read','support.review','integrations.read','integrations.retry'],ADMIN:['*']};
const ROLE_NAMES={OPERATOR:'김민수 · 운영팀',REVIEWER:'박지현 · 검수팀',MANAGER:'이민우 · 운영관리',ADMIN:'최서연 · 시스템관리'};
const queueSeed=[
{id:'W-1001',module:'MARKET',title:'고액 환불 승인 대기',subtitle:'주문 #M-260906-031 · 248,000원',priority:'HIGH',owner:'운영 관리자',capability:'refunds.approve',status:'승인 대기',time:'09:42',next:'파손 증빙과 결제 내역을 확인하고 승인 또는 반려 사유를 남깁니다.'},
{id:'W-1002',module:'OFFICE',title:'공급사 인보이스 검수',subtitle:'문서 #D-2041 · 필수값 추출 완료',priority:'MEDIUM',owner:'검수 담당자',capability:'documents.review',status:'검수 대기',time:'09:37',next:'원문과 추출값을 대조하고 승인, 수정요청 또는 반려를 결정합니다.'},
{id:'W-1003',module:'SUPPORT',title:'배송지연 문의 답변 검토',subtitle:'문의 #S-881 · 근거 3건 · 신뢰도 91%',priority:'MEDIUM',owner:'고객지원 검수자',capability:'support.review',status:'사람 검토 필요',time:'09:31',next:'근거자료와 AI 제안을 확인하고 문구를 수정한 뒤 승인 또는 반려합니다.'},
{id:'W-1004',module:'DATA_HUB',title:'주문 동기화 3회 실패',subtitle:'Run #R-1902 · warehouse-demo',priority:'HIGH',owner:'통합 운영 관리자',capability:'integrations.retry',status:'Dead Letter',time:'09:26',next:'연결 상태와 실패 원인을 확인한 뒤 안전하게 재처리하거나 운영 담당자에게 에스컬레이션합니다.'},
{id:'W-1005',module:'MARKET',title:'출고 전 주소 확인',subtitle:'주문 #M-260906-044 · 주소 검증 보류',priority:'MEDIUM',owner:'운영 담당자',capability:'orders.fulfill',status:'처리 보류',time:'09:18',next:'고객 주소 확인 후 보류를 해제하고 피킹 단계로 진행합니다.'},
{id:'W-1006',module:'OFFICE',title:'계약서 수정본 재제출',subtitle:'문서 #D-2037 · version 4',priority:'LOW',owner:'검수 담당자',capability:'documents.review',status:'재검수 대기',time:'09:04',next:'수정요청 항목이 반영됐는지 확인하고 최종 검수 결정을 남깁니다.'}
];
const auditSeed=[
{time:'09:48',actor:'최서연',module:'DATA HUB',text:'Connection warehouse-demo 상태를 점검했습니다.'},
{time:'09:42',actor:'이민우',module:'MARKET',text:'환불 요청 #RF-302를 관리자 검토함으로 이동했습니다.'},
{time:'09:37',actor:'박지현',module:'OFFICE',text:'문서 #D-2041 추출값 검수를 시작했습니다.'},
{time:'09:31',actor:'김민수',module:'SUPPORT',text:'문의 #S-881의 AI 제안과 근거 스냅샷을 열었습니다.'},
{time:'09:14',actor:'SYSTEM',module:'DATA HUB',text:'Run #R-1902가 재시도 한도에 도달해 Dead Letter로 이동했습니다.'}
];
let queue=queueSeed.map(v=>({...v}));
let selectedId=null;let moduleFilter='ALL';let riskOnly=false;
const $=s=>document.querySelector(s);const $$=s=>[...document.querySelectorAll(s)];
function can(cap){const caps=ROLE_CAPS[$('#role').value]||[];return caps.includes('*')||caps.includes(cap)}
function filteredQueue(){return queue.filter(w=>(moduleFilter==='ALL'||w.module===moduleFilter)&&(!riskOnly||w.priority==='HIGH'))}
function renderMetrics(){const visible=queue.filter(w=>w.status!=='확인 완료');$('#m-total').textContent=visible.length;$('#m-approval').textContent=visible.filter(w=>/승인|검수|검토/.test(w.status)).length;$('#m-risk').textContent=visible.filter(w=>w.priority==='HIGH').length;$('#m-done').textContent=queue.filter(w=>w.status==='확인 완료').length;$('#nav-work-count').textContent=visible.length}
function renderQueue(){const list=$('#queue-list');const rows=filteredQueue();$('#queue-count').textContent=`${rows.length}건`;list.innerHTML=rows.map(w=>`<button class="queue-item ${w.id===selectedId?'selected':''}" data-id="${w.id}" data-priority="${w.priority}" type="button"><span class="module">${w.module.replace('_',' ')}</span><span><strong>${w.title}</strong><small>${w.subtitle}</small></span><span class="priority">${w.priority==='HIGH'?'주의':w.priority==='MEDIUM'?'확인':'일반'}</span></button>`).join('')||'<div class="empty-state"><strong>조건에 맞는 업무가 없습니다.</strong><p>필터를 변경하거나 전체 보기로 돌아가세요.</p></div>';$$('.queue-item').forEach(btn=>btn.addEventListener('click',()=>selectWork(btn.dataset.id)))}
function renderAudit(){const rows=[...auditSeed];$('#audit-list').innerHTML=rows.map(a=>`<div class="audit-row"><time>${a.time}</time><span>${a.module}</span><div><strong>${a.actor}</strong><span>${a.text}</span></div></div>`).join('')}
function selectWork(id){selectedId=id;const w=queue.find(x=>x.id===id);if(!w)return;$('#empty-detail').hidden=true;$('#work-detail').hidden=false;$('#detail-module').textContent=w.module.replace('_',' ');$('#detail-title').textContent=w.title;$('#detail-subtitle').textContent=w.subtitle;$('#detail-priority').textContent=w.priority==='HIGH'?'우선 확인':w.priority==='MEDIUM'?'확인 필요':'일반';$('#detail-owner').textContent=w.owner;$('#detail-capability').textContent=w.capability;$('#detail-status').textContent=w.status;$('#detail-time').textContent=w.time;$('#detail-next').textContent=w.next;$('#open-module').href=MODULE_URLS[w.module];$('#acknowledge').disabled=w.status==='확인 완료';$('#acknowledge').textContent=w.status==='확인 완료'?'확인 완료':'확인 처리';$('#detail-message').textContent=can(w.capability)?'현재 역할에서 이 업무를 처리할 수 있습니다.':`현재 역할에는 ${w.capability} 권한이 없습니다.`;renderQueue()}
function acknowledge(){const w=queue.find(x=>x.id===selectedId);if(!w)return;if(!can(w.capability)){ $('#detail-message').textContent=`권한이 없어 처리할 수 없습니다. 필요한 권한: ${w.capability}`;return }w.status='확인 완료';$('#detail-status').textContent=w.status;$('#acknowledge').disabled=true;$('#acknowledge').textContent='확인 완료';$('#detail-message').textContent='확인 처리가 감사이력에 기록되었습니다.';auditSeed.unshift({time:'현재',actor:ROLE_NAMES[$('#role').value],module:w.module.replace('_',' '),text:`${w.id} ${w.title} 확인 처리`});renderMetrics();renderAudit();renderQueue()}
$$('[data-module]').forEach(btn=>btn.addEventListener('click',()=>{moduleFilter=btn.dataset.module;$$('[data-module]').forEach(b=>b.classList.toggle('active',b===btn));renderQueue()}));
$('#focus-risk').addEventListener('click',()=>{riskOnly=true;renderQueue()});$('#reset-filter').addEventListener('click',()=>{riskOnly=false;moduleFilter='ALL';$$('[data-module]').forEach(b=>b.classList.toggle('active',b.dataset.module==='ALL'));renderQueue()});$('#acknowledge').addEventListener('click',acknowledge);$('#role').addEventListener('change',()=>{$('#actor-name').textContent=ROLE_NAMES[$('#role').value];if(selectedId)selectWork(selectedId)});$('#menu-toggle').addEventListener('click',()=>{const side=$('.sidebar');const open=side.classList.toggle('open');$('#menu-toggle').setAttribute('aria-expanded',String(open))});$$('.sidebar a').forEach(a=>a.addEventListener('click',()=>$('.sidebar').classList.remove('open')));
renderMetrics();renderQueue();renderAudit();
