import { createStore, DomainError } from './server/store.mjs';
import { ACTION_LABELS, ROLE_LABELS, STATUS_LABELS, friendlyActor, friendlyError, uiLabel } from '../customer-ui.js';

const store = createStore();
const state = { selectedId: 1, role: 'STAFF', queueMode: null };
const $ = (id) => document.getElementById(id);
const el = {
  role:$('role'),search:$('search'),opsFilter:$('ops-filter'),paymentFilter:$('payment-filter'),fulfillmentFilter:$('fulfillment-filter'),resetFilters:$('reset-filters'),orderList:$('order-list'),visibleOrderCount:$('visible-order-count'),emptyDetail:$('empty-detail'),detail:$('detail'),orderTitle:$('order-title'),orderCustomer:$('order-customer'),orderVersion:$('order-version'),opsStatus:$('ops-status'),paymentStatus:$('payment-status'),fulfillmentStatus:$('fulfillment-status'),refundable:$('refundable'),flags:$('flags'),actions:$('actions'),holdReason:$('hold-reason'),tracking:$('tracking'),refundAmount:$('refund-amount'),refundReason:$('refund-reason'),refundNote:$('refund-note'),requestRefund:$('request-refund'),statusMessage:$('status-message'),refundList:$('refund-list'),refundRoleChip:$('refund-role-chip'),auditList:$('audit-list'),customerSummary:$('customer-summary'),orderTimeline:$('order-timeline'),mActive:$('m-active'),mHold:$('m-hold'),mUnfulfilled:$('m-unfulfilled'),mRefund:$('m-refund'),mHigh:$('m-high'),qHold:$('q-hold'),qUnfulfilled:$('q-unfulfilled'),qRefund:$('q-refund')
};
const quickFilterButtons = [...document.querySelectorAll('[data-quick-filter]')];
const money=(v,c='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
const when=(value)=>new Intl.DateTimeFormat('ko-KR',{month:'short',day:'numeric',hour:'2-digit',minute:'2-digit'}).format(new Date(value));
const node=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
const badge=(value)=>node('span',`badge ${value}`,uiLabel(value));
const actor=()=>state.role==='ADMIN'?'demo-admin':'demo-staff';
const selected=()=>{try{return state.selectedId?store.getOrder(state.selectedId):null;}catch{return null;}};
function message(text,error=false){el.statusMessage.textContent=text;el.statusMessage.dataset.error=error?'true':'false';}
function detailText(value){return STATUS_LABELS[value]??value;}
function reasonText(value){return STATUS_LABELS[value]??value;}
function readableDetail(value=''){let detail=String(value);for(const [key,label] of Object.entries(STATUS_LABELS))detail=detail.replaceAll(key,label);return detail;}
function clearFilterControls(){el.search.value='';el.opsFilter.value='';el.paymentFilter.value='';el.fulfillmentFilter.value='';state.queueMode=null;}
function syncQuickFilterState(){for(const button of quickFilterButtons){const active=button.dataset.quickFilter===state.queueMode;button.classList.toggle('active',active);button.setAttribute('aria-pressed',active?'true':'false');}}

function renderMetrics(){const m=store.metrics();el.mActive.textContent=m.active;el.mHold.textContent=m.holds;el.mUnfulfilled.textContent=m.unfulfilled;el.mRefund.textContent=m.pendingRefunds;el.mHigh.textContent=m.highValuePending;el.qHold.textContent=m.holds;el.qUnfulfilled.textContent=m.unfulfilled;el.qRefund.textContent=m.highValuePending;}
function renderOrders(){
  let orders=store.listOrders({query:el.search.value,opsStatus:el.opsFilter.value,paymentStatus:el.paymentFilter.value,fulfillmentStatus:el.fulfillmentFilter.value});
  if(state.queueMode==='unfulfilled')orders=orders.filter(order=>['UNFULFILLED','PICKING'].includes(order.fulfillmentStatus)&&!['CANCELLED','CLOSED'].includes(order.opsStatus));
  el.visibleOrderCount.textContent=`${orders.length}건`;
  el.orderList.replaceChildren();
  syncQuickFilterState();
  if(!orders.length){const empty=node('div','empty compact');const copy=node('div');copy.append(node('strong','','조건에 맞는 주문이 없습니다.'),node('span','','필터를 초기화하거나 다른 조건으로 검색해 주세요.'));const reset=node('button','empty-reset','필터 초기화');reset.type='button';reset.addEventListener('click',()=>{clearFilterControls();renderOrders();});copy.append(reset);empty.append(copy);el.orderList.append(empty);return;}
  for(const order of orders){
    const row=node('button',`order-card${order.id===state.selectedId?' active':''}`);row.type='button';row.dataset.orderId=String(order.id);row.setAttribute('aria-pressed',order.id===state.selectedId?'true':'false');row.setAttribute('aria-label',`${order.orderNo}, ${order.customerName}, ${detailText(order.fulfillmentStatus)}`);
    const main=node('div','order-main');main.append(node('strong','',order.orderNo),node('span','',`${order.customerName} · 상품 ${order.itemCount}개`));
    const payment=node('div','order-cell order-payment');payment.append(badge(order.paymentStatus));
    const shipping=node('div','order-cell order-shipping');shipping.append(badge(order.fulfillmentStatus));
    const amount=node('div','order-cell order-amount');amount.append(node('strong','',money(order.total,order.currency)),node('span','',order.opsStatus==='ON_HOLD'?reasonText(order.holdReason):detailText(order.opsStatus)));
    row.append(main,payment,shipping,amount);
    row.addEventListener('click',()=>{state.selectedId=order.id;message('');render();if(window.matchMedia('(max-width: 760px)').matches)document.querySelector('.detail-panel')?.scrollIntoView({behavior:'smooth',block:'start'});});
    el.orderList.append(row);
  }
}
function perform(action){const order=selected();if(!order)return;try{if(action==='HOLD')store.hold(order.id,{expectedVersion:order.version,reason:el.holdReason.value,actor:actor()});else if(action==='RELEASE')store.release(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='START_PICKING')store.startPicking(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='SHIP')store.ship(order.id,{expectedVersion:order.version,trackingNo:el.tracking.value,actor:actor()});else if(action==='DELIVER')store.deliver(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='RETURN')store.returnOrder(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='CANCEL'){if(!window.confirm('이 주문을 취소 처리하시겠습니까?'))return;store.cancel(order.id,{expectedVersion:order.version,actor:actor()});}message(`${ACTION_LABELS[action]??'주문 처리'}가 완료되었습니다.`);}catch(error){message(friendlyError(error),true);}render();}
function renderCustomer(order){el.customerSummary.replaceChildren();const rows=[['고객',order.customerName],['이메일',order.email],['주문 상품',`${order.itemCount}개`],['주문 금액',money(order.total,order.currency)],['운송장',order.trackingNo||'아직 등록되지 않음']];const wrap=node('div','customer-lines');for(const [label,value] of rows){const line=node('div','customer-line');line.append(node('span','',label),node('strong','',value));wrap.append(line);}el.customerSummary.append(wrap);}
function renderTimeline(order){
  const audits=store.listAudits(order.id).slice().reverse();el.orderTimeline.replaceChildren();
  const base=node('div','timeline-item');base.append(node('strong','','주문 접수'),node('span','',`${when(order.createdAt)} · 고객 주문`));el.orderTimeline.append(base);
  for(const item of audits){const row=node('div','timeline-item');const action=ACTION_LABELS[item.action]??uiLabel(item.action);const detail=readableDetail(item.detail);row.append(node('strong','',action),node('span','',`${when(item.createdAt)} · ${friendlyActor(item.actor)}${detail?` · ${detail}`:''}`));el.orderTimeline.append(row);}
}
function renderDetail(){const order=selected();el.emptyDetail.hidden=Boolean(order);el.detail.hidden=!order;if(!order)return;el.orderTitle.textContent=order.orderNo;el.orderCustomer.textContent=`${order.customerName} · ${order.email}`;el.orderVersion.textContent=`v${order.version}`;el.orderVersion.setAttribute('aria-label',`주문 버전 ${order.version}`);el.opsStatus.textContent=detailText(order.opsStatus);el.paymentStatus.textContent=detailText(order.paymentStatus);el.fulfillmentStatus.textContent=detailText(order.fulfillmentStatus);el.refundable.textContent=money(order.refundableAmount,order.currency);el.flags.replaceChildren(...(order.flags.length?order.flags.map(badge):[node('span','muted','추가 확인 항목 없음')]));el.actions.replaceChildren();for(const action of order.allowedActions.filter(x=>x!=='REQUEST_REFUND')){const b=node('button',`action ${action}`,ACTION_LABELS[action]??action);b.type='button';b.dataset.action=action;b.dataset.orderId=String(order.id);b.addEventListener('click',()=>perform(action));el.actions.append(b);}if(!el.actions.children.length)el.actions.append(node('span','muted','현재 주문에서 바로 처리할 작업이 없습니다.'));const canRefund=order.allowedActions.includes('REQUEST_REFUND');el.requestRefund.disabled=!canRefund;el.refundAmount.max=String(order.refundableAmount);if(!el.refundAmount.value||Number(el.refundAmount.value)>order.refundableAmount)el.refundAmount.value=String(Math.min(order.refundableAmount,120000));renderCustomer(order);renderTimeline(order);}
function renderRefunds(){const refunds=store.listRefunds('REQUESTED');el.refundRoleChip.textContent=ROLE_LABELS[state.role];el.refundRoleChip.dataset.role=state.role;el.refundList.replaceChildren();if(!refunds.length){el.refundList.append(node('div','empty compact','대기 중인 환불 검토가 없습니다.'));return;}for(const refund of refunds){const order=store.getOrder(refund.orderId);const card=node('article','refund-card');card.dataset.refundId=String(refund.id);const top=node('div','refund-top');const title=node('div');title.append(node('strong','',`${order.orderNo} · ${money(refund.amount,order.currency)}`),node('p','',`${reasonText(refund.reason)} · ${friendlyActor(refund.requestedBy)} 요청`));top.append(title,badge(refund.requiresApproval?'ADMIN_REQUIRED':'STANDARD_REVIEW'));const note=node('p','refund-note',refund.note||'추가 메모 없음');const decisionLabel=node('label','decision-label');decisionLabel.append(node('span','','결정 메모'));const decisionNote=node('textarea','decision-note');decisionNote.rows=2;decisionNote.maxLength=500;decisionNote.placeholder='승인·반려 판단 근거를 4자 이상 입력';decisionNote.disabled=refund.requiresApproval&&state.role!=='ADMIN';decisionLabel.append(decisionNote);const controls=node('div','refund-actions');const blocked=refund.requiresApproval&&state.role!=='ADMIN';for(const decision of ['APPROVE','REJECT']){const b=node('button',decision==='APPROVE'?'approve':'reject',decision==='APPROVE'?'환불 승인':'환불 반려');b.type='button';b.dataset.decision=decision;b.disabled=blocked;b.addEventListener('click',()=>{const decisionText=decisionNote.value.trim();if(decisionText.length<4){message('환불 결정 메모를 4자 이상 입력해 주세요.',true);decisionNote.focus();return;}try{store.decideRefund(refund.id,{expectedVersion:order.version,decision,role:state.role,decidedBy:actor(),decisionNote:decisionText});message(decision==='APPROVE'?'환불을 승인했습니다.':'환불을 반려했습니다.');}catch(error){message(error instanceof DomainError||error instanceof Error?friendlyError(error,'환불 결정을 처리할 수 없습니다.'):'환불 결정을 처리할 수 없습니다.',true);}render();});controls.append(b);}if(blocked)controls.append(node('span','role-hint','운영 관리자 권한으로 전환하면 결정 메모 입력과 승인·반려가 활성화됩니다.'));card.append(top,note,decisionLabel,controls);el.refundList.append(card);}}
function renderAudit(){el.auditList.replaceChildren();for(const item of store.listAudits().slice(0,18)){const row=node('article','audit-row');const top=node('div');top.append(node('strong','',`${ACTION_LABELS[item.action]??uiLabel(item.action)} · ${store.getOrder(item.orderId).orderNo}`),node('span','',friendlyActor(item.actor)));row.append(top,node('p','',readableDetail(item.detail)||'상태 변경'));el.auditList.append(row);}}
function render(){renderMetrics();renderOrders();renderDetail();renderRefunds();renderAudit();}
el.role.addEventListener('change',()=>{state.role=el.role.value;message(`${ROLE_LABELS[state.role]} 화면으로 전환했습니다.`);render();});
for(const input of [el.search,el.opsFilter,el.paymentFilter,el.fulfillmentFilter])input.addEventListener('input',()=>{state.queueMode=null;renderOrders();});
el.resetFilters.addEventListener('click',()=>{clearFilterControls();message('주문 필터를 초기화했습니다.');renderOrders();});
for(const button of quickFilterButtons){button.setAttribute('aria-pressed','false');button.addEventListener('click',()=>{const mode=button.dataset.quickFilter;clearFilterControls();if(mode==='hold'){el.opsFilter.value='ON_HOLD';state.queueMode='hold';renderOrders();document.querySelector('.order-list-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}else if(mode==='unfulfilled'){state.queueMode='unfulfilled';renderOrders();document.querySelector('.order-list-panel')?.scrollIntoView({behavior:'smooth',block:'start'});}else if(mode==='refund'){state.queueMode='refund';syncQuickFilterState();document.getElementById('refunds')?.scrollIntoView({behavior:'smooth',block:'start'});}});}
el.requestRefund.addEventListener('click',()=>{const order=selected();if(!order)return;try{const result=store.requestRefund(order.id,{expectedVersion:order.version,amount:Number(el.refundAmount.value),reason:el.refundReason.value,note:el.refundNote.value,actor:actor()});message(result.refund.requiresApproval?'환불 요청을 등록했습니다. 관리자 확인 목록으로 이동했습니다.':'환불 요청을 등록했습니다.');el.refundNote.value='';}catch(error){message(friendlyError(error,'환불 요청 내용을 다시 확인해 주세요.'),true);}render();});
render();
