import { createStore, DomainError } from './server/store.mjs';
import { ACTION_LABELS, ROLE_LABELS, STATUS_LABELS, friendlyActor, friendlyError, uiLabel } from '../customer-ui.js';

const store = createStore();
const state = { selectedId: 1, role: 'STAFF' };
const $ = (id) => document.getElementById(id);
const el = {
  role:$('role'),search:$('search'),opsFilter:$('ops-filter'),fulfillmentFilter:$('fulfillment-filter'),orderList:$('order-list'),emptyDetail:$('empty-detail'),detail:$('detail'),orderTitle:$('order-title'),orderCustomer:$('order-customer'),orderVersion:$('order-version'),opsStatus:$('ops-status'),paymentStatus:$('payment-status'),fulfillmentStatus:$('fulfillment-status'),refundable:$('refundable'),flags:$('flags'),actions:$('actions'),holdReason:$('hold-reason'),tracking:$('tracking'),refundAmount:$('refund-amount'),refundReason:$('refund-reason'),refundNote:$('refund-note'),requestRefund:$('request-refund'),statusMessage:$('status-message'),refundList:$('refund-list'),auditList:$('audit-list'),mActive:$('m-active'),mHold:$('m-hold'),mUnfulfilled:$('m-unfulfilled'),mRefund:$('m-refund'),mHigh:$('m-high')
};
const money=(v,c='KRW')=>new Intl.NumberFormat('ko-KR',{style:'currency',currency:c,maximumFractionDigits:0}).format(v);
const node=(tag,cls='',text='')=>{const n=document.createElement(tag);if(cls)n.className=cls;if(text)n.textContent=text;return n;};
const badge=(value)=>node('span',`badge ${value}`,uiLabel(value));
const actor=()=>state.role==='ADMIN'?'demo-admin':'demo-staff';
const selected=()=>{try{return state.selectedId?store.getOrder(state.selectedId):null;}catch{return null;}};
function message(text,error=false){el.statusMessage.textContent=text;el.statusMessage.dataset.error=error?'true':'false';}
function detailText(value){return STATUS_LABELS[value]??value;}
function reasonText(value){return STATUS_LABELS[value]??value;}

function renderMetrics(){const m=store.metrics();el.mActive.textContent=m.active;el.mHold.textContent=m.holds;el.mUnfulfilled.textContent=m.unfulfilled;el.mRefund.textContent=m.pendingRefunds;el.mHigh.textContent=m.highValuePending;}
function renderOrders(){const orders=store.listOrders({query:el.search.value,opsStatus:el.opsFilter.value,fulfillmentStatus:el.fulfillmentFilter.value});el.orderList.replaceChildren();if(!orders.length){el.orderList.append(node('div','empty compact','조건에 맞는 주문이 없습니다.'));return;}for(const order of orders){const b=node('button',`order-card${order.id===state.selectedId?' active':''}`);b.type='button';const head=node('div','order-card-head');head.append(node('strong','',order.orderNo),badge(order.fulfillmentStatus));b.append(head,node('p','',`${order.customerName} · ${money(order.total,order.currency)}`),node('small','',`${detailText(order.paymentStatus)} · 상품 ${order.itemCount}개${order.opsStatus==='ON_HOLD'?` · ${reasonText(order.holdReason)}`:''}`));b.addEventListener('click',()=>{state.selectedId=order.id;message('');render();});el.orderList.append(b);}}
function perform(action){const order=selected();if(!order)return;try{if(action==='HOLD')store.hold(order.id,{expectedVersion:order.version,reason:el.holdReason.value,actor:actor()});else if(action==='RELEASE')store.release(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='START_PICKING')store.startPicking(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='SHIP')store.ship(order.id,{expectedVersion:order.version,trackingNo:el.tracking.value,actor:actor()});else if(action==='DELIVER')store.deliver(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='RETURN')store.returnOrder(order.id,{expectedVersion:order.version,actor:actor()});else if(action==='CANCEL'){if(!window.confirm('이 주문을 취소 처리하시겠습니까?'))return;store.cancel(order.id,{expectedVersion:order.version,actor:actor()});}message(`${ACTION_LABELS[action]??'주문 처리'}가 완료되었습니다.`);}catch(error){message(friendlyError(error),true);}render();}
function renderDetail(){const order=selected();el.emptyDetail.hidden=Boolean(order);el.detail.hidden=!order;if(!order)return;el.orderTitle.textContent=order.orderNo;el.orderCustomer.textContent=`${order.customerName} · ${order.email} · ${money(order.total,order.currency)}`;el.orderVersion.textContent='';el.opsStatus.textContent=detailText(order.opsStatus);el.paymentStatus.textContent=detailText(order.paymentStatus);el.fulfillmentStatus.textContent=detailText(order.fulfillmentStatus);el.refundable.textContent=money(order.refundableAmount,order.currency);el.flags.replaceChildren(...(order.flags.length?order.flags.map(badge):[node('span','muted','추가 확인 항목 없음')]));el.actions.replaceChildren();for(const action of order.allowedActions.filter(x=>x!=='REQUEST_REFUND')){const b=node('button',`action ${action}`,ACTION_LABELS[action]??action);b.type='button';b.addEventListener('click',()=>perform(action));el.actions.append(b);}if(!el.actions.children.length)el.actions.append(node('span','muted','현재 주문에서 바로 처리할 작업이 없습니다.'));const canRefund=order.allowedActions.includes('REQUEST_REFUND');el.requestRefund.disabled=!canRefund;el.refundAmount.max=String(order.refundableAmount);if(!el.refundAmount.value||Number(el.refundAmount.value)>order.refundableAmount)el.refundAmount.value=String(Math.min(order.refundableAmount,120000));}
function renderRefunds(){const refunds=store.listRefunds('REQUESTED');el.refundList.replaceChildren();if(!refunds.length){el.refundList.append(node('div','empty compact','대기 중인 환불 검토가 없습니다.'));return;}for(const refund of refunds){const order=store.getOrder(refund.orderId);const card=node('article','refund-card');const top=node('div','refund-top');const title=node('div');title.append(node('strong','',`${order.orderNo} · ${money(refund.amount,order.currency)}`),node('p','',`${reasonText(refund.reason)} · ${friendlyActor(refund.requestedBy)} 요청`));top.append(title,badge(refund.requiresApproval?'ADMIN_REQUIRED':'STANDARD_REVIEW'));const note=node('p','refund-note',refund.note||'추가 메모 없음');const controls=node('div','refund-actions');const blocked=refund.requiresApproval&&state.role!=='ADMIN';for(const decision of ['APPROVE','REJECT']){const b=node('button',decision==='APPROVE'?'approve':'reject',decision==='APPROVE'?'환불 승인':'환불 반려');b.type='button';b.disabled=blocked;b.addEventListener('click',()=>{try{store.decideRefund(refund.id,{expectedVersion:order.version,decision,role:state.role,decidedBy:actor(),decisionNote:'공개 데모 검토'});message(decision==='APPROVE'?'환불을 승인했습니다.':'환불을 반려했습니다.');}catch(error){message(error instanceof DomainError||error instanceof Error?friendlyError(error,'환불 결정을 처리할 수 없습니다.'):'환불 결정을 처리할 수 없습니다.',true);}render();});controls.append(b);}if(blocked)controls.append(node('span','role-hint','상단 권한을 관리자로 바꾸면 결정할 수 있습니다.'));card.append(top,note,controls);el.refundList.append(card);}}
function renderAudit(){el.auditList.replaceChildren();for(const item of store.listAudits().slice(0,18)){const row=node('article','audit-row');const top=node('div');top.append(node('strong','',`${ACTION_LABELS[item.action]??uiLabel(item.action)} · ${store.getOrder(item.orderId).orderNo}`),node('span','',friendlyActor(item.actor)));let detail=item.detail||'';for(const [key,label] of Object.entries(STATUS_LABELS))detail=detail.replaceAll(key,label);row.append(top,node('p','',detail||'상태 변경'));el.auditList.append(row);}}
function render(){renderMetrics();renderOrders();renderDetail();renderRefunds();renderAudit();}
el.role.addEventListener('change',()=>{state.role=el.role.value;message(`${ROLE_LABELS[state.role]} 화면으로 전환했습니다.`);render();});for(const input of [el.search,el.opsFilter,el.fulfillmentFilter])input.addEventListener('input',renderOrders);
el.requestRefund.addEventListener('click',()=>{const order=selected();if(!order)return;try{const result=store.requestRefund(order.id,{expectedVersion:order.version,amount:Number(el.refundAmount.value),reason:el.refundReason.value,note:el.refundNote.value,actor:actor()});message(result.refund.requiresApproval?'환불 요청을 등록했습니다. 관리자 확인 목록으로 이동했습니다.':'환불 요청을 등록했습니다.');el.refundNote.value='';}catch(error){message(friendlyError(error,'환불 요청 내용을 다시 확인해 주세요.'),true);}render();});
render();
